apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csm-authorization-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csm-authorization-redis
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: csm-authorization-local-storage
  hostPath:
    path: /csm-authorization/redis
