# Copyright © 2020-2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
subjects:
  - kind: ServiceAccount
    name: <DriverDefaultReleaseName>-node
    namespace: <DriverDefaultReleaseNamespace>
roleRef:
  kind: ClusterRole
  name: <DriverDefaultReleaseName>-node
  apiGroup: rbac.authorization.k8s.io
---
# Role for Driver-specific Permissions in a Namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
---
# RoleBinding for Driver-specific Role
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
subjects:
  - kind: ServiceAccount
    name: <DriverDefaultReleaseName>-node
    namespace: <DriverDefaultReleaseNamespace>
roleRef:
  kind: Role
  name: <DriverDefaultReleaseName>-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
  annotations:
    com.dell.karavi-authorization-proxy: "true"
spec:
  selector:
    matchLabels:
      app: <DriverDefaultReleaseName>-node
  template:
    metadata:
      labels:
        app: <DriverDefaultReleaseName>-node
        driver.dellemc.com: dell-storage
        csmNamespace: <CSM_NAMESPACE>
      annotations:
        kubectl.kubernetes.io/default-container: driver
    spec:
      serviceAccount: <DriverDefaultReleaseName>-node
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: false
      containers:
        - name: driver
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_ADMIN"]
          image: quay.io/dell/container-storage-modules/csi-vxflexos:v2.14.0
          imagePullPolicy: IfNotPresent
          command: ["/csi-vxflexos.sh"]
          args:
            - "--array-config=/vxflexos-config/config"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
          env:
            - name: CSI_ENDPOINT
              value: unix://<KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com/csi_sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_PRIVATE_MOUNT_DIR
              value: "<KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com/disks"
            - name: X_CSI_ALLOW_RWO_MULTI_POD_ACCESS
              value: false
            - name: SSL_CERT_DIR
              value: /certs
            - name: X_CSI_HEALTH_MONITOR_ENABLED
              value: "<X_CSI_HEALTH_MONITOR_ENABLED>"
            - name: X_CSI_SDC_ENABLED
              value: <X_CSI_SDC_ENABLED>
            - name: X_CSI_APPROVE_SDC_ENABLED
              value: <X_CSI_APPROVE_SDC_ENABLED>
            - name: X_CSI_RENAME_SDC_ENABLED
              value: <X_CSI_RENAME_SDC_ENABLED>
            - name: X_CSI_RENAME_SDC_PREFIX
              value: <X_CSI_RENAME_SDC_PREFIX>
            - name: X_CSI_MAX_VOLUMES_PER_NODE
              value: <X_CSI_MAX_VOLUMES_PER_NODE>
            - name: GOSCALEIO_DEBUG
              value: <GOSCALEIO_DEBUG>
            - name: GOSCALEIO_SHOWHTTP
              value: <GOSCALEIO_SHOWHTTP>
            - name: X_CSI_SDC_SFTP_REPO_ENABLED
              value: <X_CSI_SDC_SFTP_REPO_ENABLED>
            - name: X_CSI_POWERFLEX_KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: RELEASE_NAME
              value: <DriverDefaultReleaseName>
          volumeMounts:
            - name: driver-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com
              mountPropagation: "Bidirectional"
            - name: volumedevices-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
              mountPropagation: "Bidirectional"
            - name: pods-path
              mountPath: <KUBELET_CONFIG_DIR>/pods
              mountPropagation: "Bidirectional"
            # will be removed if installing on OpenShift
            - name: scaleio-path-bin
              mountPath: /bin/emc/scaleio/
              readOnly: true
            - name: scaleio-path-opt
              mountPath: /opt/emc/scaleio/sdc/bin
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: vxflexos-config
              mountPath: /vxflexos-config
            - name: vxflexos-config-params
              mountPath: /vxflexos-config-params
            - name: certs
              mountPath: /certs
              readOnly: true
        - name: registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=<KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com/csi_sock
          env:
            - name: ADDRESS
              value: /csi/csi_sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: driver-path
              mountPath: /csi
        - name: sdc-monitor
          securityContext:
            privileged: true
          image: quay.io/dell/storage/powerflex/sdc:4.5.4
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_PID
              value: "1"
            - name: HOST_NET
              value: "1"
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MODE
              value: "monitoring"
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: os-release
              mountPath: /host-os-release
            - name: sdc-storage
              mountPath: /storage
            - name: udev-d
              mountPath: /rules.d
            - name: host-opt-emc-path
              mountPath: /host_opt_emc_path
      initContainers:
        - name: mdm-container
          image: quay.io/dell/container-storage-modules/csi-vxflexos:v2.14.0
          imagePullPolicy: IfNotPresent
          command: ["/csi-vxflexos.sh"]
          args:
            - "--array-config=/vxflexos-config/config"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
          env:
            - name: X_CSI_MODE
              value: mdm-info
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: vxflexos-config
              mountPath: /vxflexos-config
            - name: vxflexos-config-params
              mountPath: /vxflexos-config-params
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: mdm-dir
              mountPath: /data
        - name: sdc
          securityContext:
            privileged: true
          image: quay.io/dell/storage/powerflex/sdc:4.5.4
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              source /data/node_mdms.txt
              /files/scripts/init.sh
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MODE
              value: "config"
            - name: HOST_DRV_CFG_PATH
              value: /opt/emc/scaleio/sdc/bin
            - name: REPO_ADDRESS
              value: "<X_CSI_SFTP_REPO_ADDRESS>"
            - name: REPO_USER
              value: "<X_CSI_SFTP_REPO_USER>"
            - name: MODULE_SIGCHECK
              value: "0"
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: os-release
              mountPath: /host-os-release
            - name: sdc-storage
              mountPath: /storage
            - name: udev-d
              mountPath: /rules.d
            - name: sftp-keys
              mountPath: /config/
            - name: scaleio-path-opt
              mountPath: /host_drv_cfg_path
            - name: host-opt-emc-path
              mountPath: /host_opt_emc_path
            - name: mdm-dir
              mountPath: /data
      volumes:
        - name: registration-dir
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins_registry/
            type: DirectoryOrCreate
        - name: driver-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com
            type: DirectoryOrCreate
        - name: volumedevices-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
            type: DirectoryOrCreate
        - name: pods-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/pods
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        # will be removed if installing on OpenShift
        - name: scaleio-path-bin
          hostPath:
            path: /bin/emc/scaleio/
            type: DirectoryOrCreate
        - name: scaleio-path-opt
          hostPath:
            path: /opt/emc/scaleio/sdc/bin
            type: DirectoryOrCreate
        - name: sdc-storage
          hostPath:
            path: /var/emc-scaleio
            type: DirectoryOrCreate
        - name: udev-d
          hostPath:
            path: /etc/udev/rules.d
            type: Directory
        # will be removed if sftp is not enabled
        - name: sftp-keys
          projected:
            defaultMode: 384
            sources:
              - secret:
                  name: sdcsftprepo-private-secret
              - secret:
                  name: sdcsftprepo-public-secret
        - name: os-release
          hostPath:
            path: /etc/os-release
            type: File
        - name: host-opt-emc-path
          hostPath:
            path: /opt/emc
            type: Directory
        - name: vxflexos-config
          secret:
            secretName: <DriverDefaultReleaseName>-config
        - name: vxflexos-config-params
          configMap:
            name: <DriverDefaultReleaseName>-config-params
        - name: usr-bin
          hostPath:
            path: /usr/bin
            type: Directory
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: var-run
          hostPath:
            path: /var/run
            type: Directory
        - name: mdm-dir
          emptyDir: {}
        - name: certs
          projected:
            sources:
              - secret:
                  name: <DriverDefaultReleaseName>-certs-0
                  items:
                    - key: cert-0
                      path: cert-0
