apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: cosi
  namespace: dell-cosi
spec:
  driver:
    csiDriverType: "cosi"
    configVersion: v1.0.0
    replicas: 2
    forceRemoveDriver: true
    common:
      image: "quay.io/dell/container-storage-modules/cosi:v1.0.0"
      imagePullPolicy: IfNotPresent
      # Node selector for scheduling the COSI driver pod.
      nodeSelector: {}
      # Tolerations for scheduling the COSI driver pod.
      tolerations: []
      envs:
        # COSI driver log level.
        # Options are "PANIC", "FATAL", "ERROR", "WARN", "INFO",
        # "DEBUG", and "TRACE".
        - name: COSI_LOG_LEVEL
          value: "INFO"
        # COSI driver log format
        # Allowed values: "TEXT" or "JSON"
        # Default value: "TEXT"
        - name: COSI_LOG_FORMAT
          value: "TEXT"
        # OTEL_COLLECTOR_ADDRESS is the gRPC endpoint for the OTEL Collector.
        # Example: "otel-collector.namespace:4317"
        # Default: ""
        - name: OTEL_COLLECTOR_ADDRESS
          value: ""
    sideCars:
      - name: objectstorage-provisioner-sidecar
        image: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar:release-0.2
        imagePullPolicy: IfNotPresent
