# Copyright © 2020-2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: karavi-metrics-powerscale-controller
  namespace: <CSM_NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karavi-metrics-powerscale-controller
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karavi-metrics-powerscale-controller
subjects:
  - kind: ServiceAccount
    name: karavi-metrics-powerscale-controller
    namespace: <CSM_NAMESPACE>
roleRef:
  kind: ClusterRole
  name: karavi-metrics-powerscale-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karavi-metrics-powerscale-controller
  namespace: <CSM_NAMESPACE>
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karavi-metrics-powerscale-controller
  namespace: <CSM_NAMESPACE>
subjects:
  - kind: ServiceAccount
    name: karavi-metrics-powerscale-controller
    namespace: <CSM_NAMESPACE>
roleRef:
  kind: Role
  name: karavi-metrics-powerscale-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: karavi-metrics-powerscale
    app.kubernetes.io/instance: karavi
  name: karavi-metrics-powerscale
  namespace: <CSM_NAMESPACE>
spec:
  type: ClusterIP
  ports:
    - name: karavi-metrics-powerscale
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: karavi-metrics-powerscale
    app.kubernetes.io/instance: karavi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karavi-metrics-powerscale-configmap
  namespace: <CSM_NAMESPACE>
data:
  karavi-metrics-powerscale.yaml: |
    COLLECTOR_ADDR: <COLLECTOR_ADDRESS>
    PROVISIONER_NAMES: csi-isilon.dellemc.com
    POWERSCALE_MAX_CONCURRENT_QUERIES: <POWERSCALE_MAX_CONCURRENT_QUERIES>
    POWERSCALE_CAPACITY_METRICS_ENABLED: <POWERSCALE_CAPACITY_METRICS_ENABLED>
    POWERSCALE_PERFORMANCE_METRICS_ENABLED: <POWERSCALE_PERFORMANCE_METRICS_ENABLED>
    POWERSCALE_TOPOLOGY_METRICS_ENABLED: <POWERSCALE_TOPOLOGY_METRICS_ENABLED>
    POWERSCALE_TOPOLOGY_METRICS_POLL_FREQUENCY: <POWERSCALE_TOPOLOGY_METRICS_POLL_FREQUENCY>
    POWERSCALE_CLUSTER_CAPACITY_POLL_FREQUENCY: <POWERSCALE_CLUSTER_CAPACITY_POLL_FREQUENCY>
    POWERSCALE_CLUSTER_PERFORMANCE_POLL_FREQUENCY: <POWERSCALE_CLUSTER_PERFORMANCE_POLL_FREQUENCY>
    POWERSCALE_QUOTA_CAPACITY_POLL_FREQUENCY: <POWERSCALE_QUOTA_CAPACITY_POLL_FREQUENCY>
    POWERSCALE_ISICLIENT_INSECURE: <ISICLIENT_INSECURE>
    POWERSCALE_ISICLIENT_AUTH_TYPE: <ISICLIENT_AUTH_TYPE>
    POWERSCALE_ISICLIENT_VERBOSE: <ISICLIENT_VERBOSE>
    LOG_LEVEL: <POWERSCALE_LOG_LEVEL>
    LOG_FORMAT: <POWERSCALE_LOG_FORMAT>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: <DriverDefaultReleaseName>-config-params
  namespace: <CSM_NAMESPACE>
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karavi-metrics-powerscale
  namespace: <CSM_NAMESPACE>
  labels:
    app.kubernetes.io/name: karavi-metrics-powerscale
    app.kubernetes.io/instance: karavi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karavi-metrics-powerscale
      app.kubernetes.io/instance: karavi
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karavi-metrics-powerscale
        app.kubernetes.io/instance: karavi
        csm: <NAME>
        csmNamespace: <CSM_NAMESPACE>
    spec:
      serviceAccount: karavi-metrics-powerscale-controller
      containers:
        - name: karavi-metrics-powerscale
          image: quay.io/dell/container-storage-modules/csm-metrics-powerscale:v1.10.0
          resources: {}
          env:
            - name: POWERSCALE_METRICS_ENDPOINT
              value: "karavi-metrics-powerscale"
            - name: POWERSCALE_METRICS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TLS_ENABLED
              value: "true"
          volumeMounts:
            - name: isilon-creds
              mountPath: /isilon-creds
            - name: tls-secret
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: karavi-metrics-powerscale-configmap
              mountPath: /etc/config
      volumes:
        - name: isilon-creds
          secret:
            secretName: <DriverDefaultReleaseName>-creds
        - name: tls-secret
          secret:
            secretName: otel-collector-tls
            items:
              - key: tls.crt
                path: cert.crt
        - name: karavi-metrics-powerscale-configmap
          configMap:
            name: karavi-metrics-powerscale-configmap
        - name: csi-isilon-config-params
          configMap:
            name: <DriverDefaultReleaseName>-config-params
      restartPolicy: Always
status: {}
