apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: <CSM_NAMESPACE>
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <OBSERVABILITY_SECRET_PREFIX>
  namespace: <CSM_NAMESPACE>
spec:
  secretName: <OBSERVABILITY_SECRET_PREFIX>-tls
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
      - dell
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - <OBSERVABILITY_SECRET_PREFIX>
    - <OBSERVABILITY_SECRET_PREFIX>.karavi.svc.kubernetes.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
