# Copyright © 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: <DriverDefaultReleaseName>-metrics-monitor
  namespace: <DriverDefaultReleaseNamespace>
  labels:
    name: <DriverDefaultReleaseName>-controller
spec:
  selector:
    matchLabels:
      name: <DriverDefaultReleaseName>-controller
  namespaceSelector:
    matchNames:
      - <DriverDefaultReleaseNamespace>
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: ""
      path: /metrics
