---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
registries:
  github:
    type: git
    url: https://eos2git.cec.lab.emc.com
    username: x-access-token
    password: ${{ secrets.DELL_GITHUB_TOKEN_RW }}
    # gradle-artifactory:
    #   type: maven-repository
    #   url: https://isgdev.artifactory.cec.lab.emc.com/artifactory/my-gradle-registry
    #   username: svc_npdrp
    #   password: ${{ secrets.DELL_TECHOPS_ARTIFACTORY_TOKEN_RW_SVC_NPDRP }}
    # npm-artifactory:
    #   type: npm-registry
    #   url: https://isgdev.artifactory.cec.lab.emc.com/artifactory/my-npm-registry
    #   username: svc_npdrp
    #   password: ${{ secrets.DELL_TECHOPS_ARTIFACTORY_TOKEN_RW_SVC_NPDRP }}
    # python-artifactory:
    #   type: python-index
    #   url: https://isgdev.artifactory.cec.lab.emc.com/artifactory/api/pypi/cyclone-pypi/simples
    #   username: svc_npdrp
    #   password: ${{ secrets.DELL_TECHOPS_ARTIFACTORY_TOKEN_RW_SVC_NPDRP }}
    # dockerhub: # Define access for a private registry
    #   type: docker-registry
    #   url: https://harbor.dell.com/
    #   username: svc_npdrp
    #   password: ${{ secrets.DELL_HARBOR_TOKEN_RW_SVC_NPDRP }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DDRP-14968]"
    groups:
      all-updates:
        patterns:
          - "*"
    registries:
      - github
    ignore:
      # For GitHub Actions, upload-artifact@v4+ and download-artifact@v4+ are not currently supported on GHES
      - dependency-name: "actions/upload-artifact"
        versions: ">= 4"
      - dependency-name: "actions/download-artifact"
        versions: ">= 4"
      - dependency-name: "actions/checkout"
        versions: ">= 4"
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
    commit-message:
      prefix: "[DDRP-14968]"
    allow:
      # Allow direct updates for packages
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
      - dependency-name: "github.com/container-storage-interface/spec"
      - dependency-name: "github.com/kubernetes-csi/csi-lib-utils"
    groups:
      all-updates:
        patterns:
          - "*"
    registries:
      - github
  - package-ecosystem: "docker"
    directory: "/controller" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DDRP-14968]"
    groups:
      all-updates:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DDRP-14968]"
    groups:
      all-updates:
        patterns:
          - "*"
