# Copyright © 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Config to be used in CSM Powermax Reverseproxy
# Fill in the appropriate values, refer to docs if required
# Create the configmap using following cmd
# kubectl/oc create configmap powermax-reverseproxy-config --from-file config.yaml -n <namespace>
mode: StandAlone  # Mode for the reverseproxy, should not be changed
port: 2222
logLevel: debug
logFormat: text
standAloneConfig:
  storageArrays:
    - storageArrayId: "000000000001"  # arrayID
      primaryURL: https://primary-1.unisphe.re:8443  # primary unisphere for arrayID
      backupURL: https://backup-1.unisphe.re:8443  # backup unisphere for arrayID
      proxyCredentialSecrets:
        - proxy-secret-11  # credential secret for primary unisphere, e.g., powermax-creds
        - proxy-secret-12  # credential secret for backup unisphere, e.g., powermax-creds
    - storageArrayId: "000000000002"
      primaryURL: https://primary-2.unisphe.re:8443
      backupURL: https://backup-2.unisphe.re:8443
      proxyCredentialSecrets:
        - proxy-secret-21
        - proxy-secret-22
  managementServers:
    - url: https://primary-1.unisphe.re:8443  # primary unisphere endpoint
      arrayCredentialSecret: primary-1-secret  # credential secret, e.g., powermax-creds
      skipCertificateValidation: true
    - url: https://backup-1.unisphe.re:8443  # backup unisphere endpoint
      arrayCredentialSecret: backup-1-secret  # credential secret, e.g., powermax-creds
      skipCertificateValidation: false  # value false, to verify unisphere certificate and provide certSecret
      certSecret: primary-certs  # unisphere verification certificate
    - url: https://primary-2.unisphe.re:8443
      arrayCredentialSecret: primary-2-secret
      skipCertificateValidation: true
    - url: https://backup-2.unisphe.re:8443
      arrayCredentialSecret: backup-2-secret
      skipCertificateValidation: false
      certSecret: primary-certs
