# Copyright © 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [ "security.openshift.io" ]
    resourceNames: [ "privileged" ]
    resources: [ "securitycontextconstraints" ]
    verbs: [ "use" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
subjects:
  - kind: ServiceAccount
    name: <DriverDefaultReleaseName>-node
    namespace: <DriverDefaultReleaseNamespace>
roleRef:
  kind: ClusterRole
  name: <DriverDefaultReleaseName>-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
spec:
  selector:
    matchLabels:
      app: <DriverDefaultReleaseName>-node
  template:
    metadata:
      labels:
        app: <DriverDefaultReleaseName>-node
    spec:
      serviceAccount: <DriverDefaultReleaseName>-node
      #nodeSelector:
      #tolerations:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: driver
          command: ["/csi-powermax.sh"]
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: dellemc/csi-powermax:v2.9.0
          imagePullPolicy: IfNotPresent
          env:
            - name: X_CSI_POWERMAX_DRIVER_NAME
              value: csi-powermax.dellemc.com
            - name: CSI_ENDPOINT
              value: unix://<KUBELET_CONFIG_DIR>/plugins/powermax.emc.dell.com/csi_sock
            - name: X_CSI_MANAGED_ARRAYS
              value: "<X_CSI_MANAGED_ARRAY>"
            - name: X_CSI_POWERMAX_ENDPOINT
              value: "<X_CSI_POWERMAX_ENDPOINT>"
            - name: X_CSI_K8S_CLUSTER_PREFIX
              value: "<X_CSI_K8S_CLUSTER_PREFIX>"
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_PRIVATE_MOUNT_DIR
              value: "<KUBELET_CONFIG_DIR>/plugins/powermax.emc.dell.com/disks"
            - name: X_CSI_POWERMAX_SKIP_CERTIFICATE_VALIDATION
              value: true
            - name: X_CSI_POWERMAX_USER
              valueFrom:
                secretKeyRef:
                  name: powermax-creds
                  key: username
            - name: X_CSI_POWERMAX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: powermax-creds
                  key: password
            - name: X_CSI_POWERMAX_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: X_CSI_POWERMAX_ISCSI_ENABLE_CHAP
              value: "<X_CSI_POWERMAX_ISCSI_ENABLE_CHAP>"
            - name: X_CSI_POWERMAX_PROXY_SERVICE_NAME
              value: "csipowermax-reverseproxy"
            - name: X_CSI_NODE_CHROOT
              value: noderoot
            - name: X_CSI_GRPC_MAX_THREADS
              value: "50"
            - name: X_CSI_TRANSPORT_PROTOCOL
              value: "<X_CSI_TRANSPORT_PROTOCOL>"
            - name: SSL_CERT_DIR
              value: /certs
            - name: X_CSI_POWERMAX_CONFIG_PATH
              value: /powermax-config-params/driver-config-params.yaml
            - name: X_CSI_POWERMAX_TOPOLOGY_CONFIG_PATH
              value: /node-topology-config/topologyConfig.yaml
            - name: X_CSI_IG_NODENAME_TEMPLATE
              value: "<X_CSI_IG_NODENAME_TEMPLATE>"
            - name: X_CSI_IG_MODIFY_HOSTNAME
              value: "<X_CSI_IG_MODIFY_HOSTNAME>"
            - name: X_CSI_POWERMAX_PORTGROUPS
              value: "<X_CSI_POWERMAX_PORTGROUPS>"
            - name: X_CSI_HEALTH_MONITOR_ENABLED
              value: "<X_CSI_HEALTH_MONITOR_ENABLED>"
            - name: X_CSI_MAX_VOLUMES_PER_NODE
              value: "<X_CSI_MAX_VOLUMES_PER_NODE>"
            - name: X_CSI_TOPOLOGY_CONTROL_ENABLED
              value: "<X_CSI_TOPOLOGY_CONTROL_ENABLED>"
            - name: X_CSI_VSPHERE_ENABLED
              value: "<X_CSI_VSPHERE_ENABLED>"
            - name: X_CSI_VSPHERE_PORTGROUP
              value: "<X_CSI_VSPHERE_PORTGROUP>"
            - name: X_CSI_VCENTER_HOST
              value: "<X_CSI_VCENTER_HOST>"
            - name: X_CSI_VSPHERE_HOSTNAME
              value: "<X_CSI_VSPHERE_HOSTNAME>"
            - name: X_CSI_VCENTER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: vcenter-creds
                  optional: true
            - name: X_CSI_VCENTER_PWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: vcenter-creds
                  optional: true
          volumeMounts:
            - name: driver-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/powermax.emc.dell.com
            - name: volumedevices-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
              mountPropagation: "Bidirectional"
            - name: pods-path
              mountPath: <KUBELET_CONFIG_DIR>/pods
              mountPropagation: "Bidirectional"
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
            - name: noderoot
              mountPath: /noderoot
            - name: dbus-socket
              mountPath: /run/dbus/system_bus_socket
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: powermax-config-params
              mountPath: /powermax-config-params
            - name: node-topology-config
              mountPath: /node-topology-config
        - name: registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=<KUBELET_CONFIG_DIR>/plugins/powermax.emc.dell.com/csi_sock
          env:
            - name: ADDRESS
              value: /csi/csi_sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: driver-path
              mountPath: /csi
      volumes:
        - name: registration-dir
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins_registry/
            type: DirectoryOrCreate
        - name: driver-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/powermax.emc.dell.com
            type: DirectoryOrCreate
        - name: volumedevices-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
            type: DirectoryOrCreate
        - name: pods-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/pods
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: noderoot
          hostPath:
            path: /
            type: Directory
        - name: dbus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
            type: Socket
        - name: certs
          secret:
            secretName: <DriverDefaultReleaseName>-certs
            optional: true
        - name: powermax-config-params
          configMap:
             name: <DriverDefaultReleaseName>-config-params
        - name: node-topology-config
          configMap:
             name: node-topology-config
             optional: true
