//go:build !ignore_autogenerated

// Copyright © 2021-2026 Dell Inc. or its subsidiaries. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverSpec) DeepCopyInto(out *CSIDriverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverSpec.
func (in *CSIDriverSpec) DeepCopy() *CSIDriverSpec {
	if in == nil {
		return nil
	}
	out := new(CSIDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecretProviderClass) DeepCopyInto(out *ConfigSecretProviderClass) {
	*out = *in
	if in.Conjur != nil {
		in, out := &in.Conjur, &out.Conjur
		*out = new(ConjurConfigPath)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecretProviderClass.
func (in *ConfigSecretProviderClass) DeepCopy() *ConfigSecretProviderClass {
	if in == nil {
		return nil
	}
	out := new(ConfigSecretProviderClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConjurConfigPath) DeepCopyInto(out *ConjurConfigPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConjurConfigPath.
func (in *ConjurConfigPath) DeepCopy() *ConjurConfigPath {
	if in == nil {
		return nil
	}
	out := new(ConjurConfigPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConjurCredentialPath) DeepCopyInto(out *ConjurCredentialPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConjurCredentialPath.
func (in *ConjurCredentialPath) DeepCopy() *ConjurCredentialPath {
	if in == nil {
		return nil
	}
	out := new(ConjurCredentialPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConjurSecretProviderClass) DeepCopyInto(out *ConjurSecretProviderClass) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]ConjurCredentialPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConjurSecretProviderClass.
func (in *ConjurSecretProviderClass) DeepCopy() *ConjurSecretProviderClass {
	if in == nil {
		return nil
	}
	out := new(ConjurSecretProviderClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStorageModule) DeepCopyInto(out *ContainerStorageModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStorageModule.
func (in *ContainerStorageModule) DeepCopy() *ContainerStorageModule {
	if in == nil {
		return nil
	}
	out := new(ContainerStorageModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerStorageModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStorageModuleList) DeepCopyInto(out *ContainerStorageModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerStorageModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStorageModuleList.
func (in *ContainerStorageModuleList) DeepCopy() *ContainerStorageModuleList {
	if in == nil {
		return nil
	}
	out := new(ContainerStorageModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerStorageModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStorageModuleSpec) DeepCopyInto(out *ContainerStorageModuleSpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStorageModuleSpec.
func (in *ContainerStorageModuleSpec) DeepCopy() *ContainerStorageModuleSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerStorageModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStorageModuleStatus) DeepCopyInto(out *ContainerStorageModuleStatus) {
	*out = *in
	out.ControllerStatus = in.ControllerStatus
	out.NodeStatus = in.NodeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStorageModuleStatus.
func (in *ContainerStorageModuleStatus) DeepCopy() *ContainerStorageModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerStorageModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerTemplate) DeepCopyInto(out *ContainerTemplate) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ProxyServerIngress != nil {
		in, out := &in.ProxyServerIngress, &out.ProxyServerIngress
		*out = make([]ProxyServerIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(ProxyServerGateway)
		(*in).DeepCopyInto(*out)
	}
	if in.Vaults != nil {
		in, out := &in.Vaults, &out.Vaults
		*out = make([]Vault, len(*in))
		copy(*out, *in)
	}
	if in.SecretProviderClasses != nil {
		in, out := &in.SecretProviderClasses, &out.SecretProviderClasses
		*out = new(StorageSystemSecretProviderClasses)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RedisSecretProviderClass != nil {
		in, out := &in.RedisSecretProviderClass, &out.RedisSecretProviderClass
		*out = make([]RedisSecretProviderClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigSecretProviderClass != nil {
		in, out := &in.ConfigSecretProviderClass, &out.ConfigSecretProviderClass
		*out = make([]ConfigSecretProviderClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerTemplate.
func (in *ContainerTemplate) DeepCopy() *ContainerTemplate {
	if in == nil {
		return nil
	}
	out := new(ContainerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Driver) DeepCopyInto(out *Driver) {
	*out = *in
	if in.CSIDriverSpec != nil {
		in, out := &in.CSIDriverSpec, &out.CSIDriverSpec
		*out = new(CSIDriverSpec)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(ContainerTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(ContainerTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(ContainerTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.SideCars != nil {
		in, out := &in.SideCars, &out.SideCars
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotClass != nil {
		in, out := &in.SnapshotClass, &out.SnapshotClass
		*out = make([]SnapshotClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ForceRemoveDriver != nil {
		in, out := &in.ForceRemoveDriver, &out.ForceRemoveDriver
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(DriverMetrics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Driver.
func (in *Driver) DeepCopy() *Driver {
	if in == nil {
		return nil
	}
	out := new(Driver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverMetrics) DeepCopyInto(out *DriverMetrics) {
	*out = *in
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(LeaderElectionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayMonitoring != nil {
		in, out := &in.GatewayMonitoring, &out.GatewayMonitoring
		*out = new(GatewayMonitoringConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(MetricsCollectionConfig)
		**out = **in
	}
	if in.Array != nil {
		in, out := &in.Array, &out.Array
		*out = new(MetricsArrayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(MetricsServiceMonitorConfig)
		**out = **in
	}
	if in.PodMonitor != nil {
		in, out := &in.PodMonitor, &out.PodMonitor
		*out = new(MetricsPodMonitorConfig)
		**out = **in
	}
	if in.PrometheusRule != nil {
		in, out := &in.PrometheusRule, &out.PrometheusRule
		*out = new(MetricsPrometheusRuleConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverMetrics.
func (in *DriverMetrics) DeepCopy() *DriverMetrics {
	if in == nil {
		return nil
	}
	out := new(DriverMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayMonitoringConfig) DeepCopyInto(out *GatewayMonitoringConfig) {
	*out = *in
	if in.LeaderElectionEnabled != nil {
		in, out := &in.LeaderElectionEnabled, &out.LeaderElectionEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayMonitoringConfig.
func (in *GatewayMonitoringConfig) DeepCopy() *GatewayMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsArrayConfig) DeepCopyInto(out *MetricsArrayConfig) {
	*out = *in
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = new(MetricsCircuitBreakerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsArrayConfig.
func (in *MetricsArrayConfig) DeepCopy() *MetricsArrayConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsArrayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsCircuitBreakerConfig) DeepCopyInto(out *MetricsCircuitBreakerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsCircuitBreakerConfig.
func (in *MetricsCircuitBreakerConfig) DeepCopy() *MetricsCircuitBreakerConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsCircuitBreakerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsCollectionConfig) DeepCopyInto(out *MetricsCollectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsCollectionConfig.
func (in *MetricsCollectionConfig) DeepCopy() *MetricsCollectionConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsCollectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsPodMonitorConfig) DeepCopyInto(out *MetricsPodMonitorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsPodMonitorConfig.
func (in *MetricsPodMonitorConfig) DeepCopy() *MetricsPodMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsPodMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsPrometheusRuleConfig) DeepCopyInto(out *MetricsPrometheusRuleConfig) {
	*out = *in
	if in.QuotaWarningThreshold != nil {
		in, out := &in.QuotaWarningThreshold, &out.QuotaWarningThreshold
		*out = new(int32)
		**out = **in
	}
	if in.QuotaCriticalThreshold != nil {
		in, out := &in.QuotaCriticalThreshold, &out.QuotaCriticalThreshold
		*out = new(int32)
		**out = **in
	}
	if in.NodepoolWarningThreshold != nil {
		in, out := &in.NodepoolWarningThreshold, &out.NodepoolWarningThreshold
		*out = new(int32)
		**out = **in
	}
	if in.NodepoolCriticalThreshold != nil {
		in, out := &in.NodepoolCriticalThreshold, &out.NodepoolCriticalThreshold
		*out = new(int32)
		**out = **in
	}
	if in.ApplianceWarningThreshold != nil {
		in, out := &in.ApplianceWarningThreshold, &out.ApplianceWarningThreshold
		*out = new(int32)
		**out = **in
	}
	if in.ApplianceCriticalThreshold != nil {
		in, out := &in.ApplianceCriticalThreshold, &out.ApplianceCriticalThreshold
		*out = new(int32)
		**out = **in
	}
	if in.APIErrorRateThreshold != nil {
		in, out := &in.APIErrorRateThreshold, &out.APIErrorRateThreshold
		*out = new(int32)
		**out = **in
	}
	if in.APIErrorRateWindow != nil {
		in, out := &in.APIErrorRateWindow, &out.APIErrorRateWindow
		*out = new(string)
		**out = **in
	}
	if in.CPUWarningThreshold != nil {
		in, out := &in.CPUWarningThreshold, &out.CPUWarningThreshold
		*out = new(int32)
		**out = **in
	}
	if in.MemoryWarningThreshold != nil {
		in, out := &in.MemoryWarningThreshold, &out.MemoryWarningThreshold
		*out = new(int64)
		**out = **in
	}
	if in.NFSv3LatencyWarningSeconds != nil {
		in, out := &in.NFSv3LatencyWarningSeconds, &out.NFSv3LatencyWarningSeconds
		*out = new(int32)
		**out = **in
	}
	if in.NFSv4LatencyWarningSeconds != nil {
		in, out := &in.NFSv4LatencyWarningSeconds, &out.NFSv4LatencyWarningSeconds
		*out = new(int32)
		**out = **in
	}
	if in.DriverCrashLoopRestartThreshold != nil {
		in, out := &in.DriverCrashLoopRestartThreshold, &out.DriverCrashLoopRestartThreshold
		*out = new(int32)
		**out = **in
	}
	if in.DriverCrashLoopWindow != nil {
		in, out := &in.DriverCrashLoopWindow, &out.DriverCrashLoopWindow
		*out = new(string)
		**out = **in
	}
	if in.RestartCountThreshold != nil {
		in, out := &in.RestartCountThreshold, &out.RestartCountThreshold
		*out = new(int32)
		**out = **in
	}
	if in.PoolCapacityWarningPercent != nil {
		in, out := &in.PoolCapacityWarningPercent, &out.PoolCapacityWarningPercent
		*out = new(int32)
		**out = **in
	}
	if in.PoolCapacityCriticalPercent != nil {
		in, out := &in.PoolCapacityCriticalPercent, &out.PoolCapacityCriticalPercent
		*out = new(int32)
		**out = **in
	}
	if in.ThinRatioWarningThreshold != nil {
		in, out := &in.ThinRatioWarningThreshold, &out.ThinRatioWarningThreshold
		*out = new(string)
		**out = **in
	}
	if in.DataReductionDegradedThreshold != nil {
		in, out := &in.DataReductionDegradedThreshold, &out.DataReductionDegradedThreshold
		*out = new(string)
		**out = **in
	}
	if in.RCGLagWarningSeconds != nil {
		in, out := &in.RCGLagWarningSeconds, &out.RCGLagWarningSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RCGBandwidthWarningKBps != nil {
		in, out := &in.RCGBandwidthWarningKBps, &out.RCGBandwidthWarningKBps
		*out = new(int64)
		**out = **in
	}
	if in.RCGLatencyWarningSeconds != nil {
		in, out := &in.RCGLatencyWarningSeconds, &out.RCGLatencyWarningSeconds
		*out = new(string)
		**out = **in
	}
	if in.VolumeOperationFailureThreshold != nil {
		in, out := &in.VolumeOperationFailureThreshold, &out.VolumeOperationFailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.StorageGroupCapacityWarning != nil {
		in, out := &in.StorageGroupCapacityWarning, &out.StorageGroupCapacityWarning
		*out = new(int32)
		**out = **in
	}
	if in.StorageGroupCapacityCritical != nil {
		in, out := &in.StorageGroupCapacityCritical, &out.StorageGroupCapacityCritical
		*out = new(int32)
		**out = **in
	}
	if in.SRPSnapshotCapacityWarning != nil {
		in, out := &in.SRPSnapshotCapacityWarning, &out.SRPSnapshotCapacityWarning
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsPrometheusRuleConfig.
func (in *MetricsPrometheusRuleConfig) DeepCopy() *MetricsPrometheusRuleConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsPrometheusRuleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServiceMonitorConfig) DeepCopyInto(out *MetricsServiceMonitorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServiceMonitorConfig.
func (in *MetricsServiceMonitorConfig) DeepCopy() *MetricsServiceMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsServiceMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ModuleMetrics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleMetrics) DeepCopyInto(out *ModuleMetrics) {
	*out = *in
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(MetricsCollectionConfig)
		**out = **in
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(MetricsServiceMonitorConfig)
		**out = **in
	}
	if in.PodMonitor != nil {
		in, out := &in.PodMonitor, &out.PodMonitor
		*out = new(MetricsPodMonitorConfig)
		**out = **in
	}
	if in.PrometheusRule != nil {
		in, out := &in.PrometheusRule, &out.PrometheusRule
		*out = new(ModulePrometheusRuleConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleMetrics.
func (in *ModuleMetrics) DeepCopy() *ModuleMetrics {
	if in == nil {
		return nil
	}
	out := new(ModuleMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePrometheusRuleConfig) DeepCopyInto(out *ModulePrometheusRuleConfig) {
	*out = *in
	if in.ConnectivitySuccessRatio != nil {
		in, out := &in.ConnectivitySuccessRatio, &out.ConnectivitySuccessRatio
		*out = new(int32)
		**out = **in
	}
	if in.RPOThresholdSeconds != nil {
		in, out := &in.RPOThresholdSeconds, &out.RPOThresholdSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SRDFMinBandwidth != nil {
		in, out := &in.SRDFMinBandwidth, &out.SRDFMinBandwidth
		*out = new(int64)
		**out = **in
	}
	if in.SRDFLagSeconds != nil {
		in, out := &in.SRDFLagSeconds, &out.SRDFLagSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AuthFailureRateThreshold != nil {
		in, out := &in.AuthFailureRateThreshold, &out.AuthFailureRateThreshold
		*out = new(int32)
		**out = **in
	}
	if in.AuthLatencyQuantile != nil {
		in, out := &in.AuthLatencyQuantile, &out.AuthLatencyQuantile
		*out = new(int32)
		**out = **in
	}
	if in.AuthLatencyThresholdSeconds != nil {
		in, out := &in.AuthLatencyThresholdSeconds, &out.AuthLatencyThresholdSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePrometheusRuleConfig.
func (in *ModulePrometheusRuleConfig) DeepCopy() *ModulePrometheusRuleConfig {
	if in == nil {
		return nil
	}
	out := new(ModulePrometheusRuleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodStatus) DeepCopyInto(out *PodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodStatus.
func (in *PodStatus) DeepCopy() *PodStatus {
	if in == nil {
		return nil
	}
	out := new(PodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyServerGateway) DeepCopyInto(out *ProxyServerGateway) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyServerGateway.
func (in *ProxyServerGateway) DeepCopy() *ProxyServerGateway {
	if in == nil {
		return nil
	}
	out := new(ProxyServerGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyServerIngress) DeepCopyInto(out *ProxyServerIngress) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyServerIngress.
func (in *ProxyServerIngress) DeepCopy() *ProxyServerIngress {
	if in == nil {
		return nil
	}
	out := new(ProxyServerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretProviderClass) DeepCopyInto(out *RedisSecretProviderClass) {
	*out = *in
	if in.Conjur != nil {
		in, out := &in.Conjur, &out.Conjur
		*out = new(ConjurCredentialPath)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretProviderClass.
func (in *RedisSecretProviderClass) DeepCopy() *RedisSecretProviderClass {
	if in == nil {
		return nil
	}
	out := new(RedisSecretProviderClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotClass) DeepCopyInto(out *SnapshotClass) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotClass.
func (in *SnapshotClass) DeepCopy() *SnapshotClass {
	if in == nil {
		return nil
	}
	out := new(SnapshotClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSystemSecretProviderClasses) DeepCopyInto(out *StorageSystemSecretProviderClasses) {
	*out = *in
	if in.Vaults != nil {
		in, out := &in.Vaults, &out.Vaults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conjurs != nil {
		in, out := &in.Conjurs, &out.Conjurs
		*out = make([]ConjurSecretProviderClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSystemSecretProviderClasses.
func (in *StorageSystemSecretProviderClasses) DeepCopy() *StorageSystemSecretProviderClasses {
	if in == nil {
		return nil
	}
	out := new(StorageSystemSecretProviderClasses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vault) DeepCopyInto(out *Vault) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vault.
func (in *Vault) DeepCopy() *Vault {
	if in == nil {
		return nil
	}
	out := new(Vault)
	in.DeepCopyInto(out)
	return out
}
