apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: csi-vxflexos.dellemc.com
spec:
    attachRequired: true
    podInfoOnMount: true
    volumeLifecycleModes: 
    - Persistent
    - Ephemeral