apiVersion: v1
data:
  csm-config-params.yaml: |-
    CONCURRENT_POWERFLEX_REQUESTS: 10
    CONCURRENT_POWERSCALE_REQUESTS: 10
    LOG_LEVEL: debug
    STORAGE_CAPACITY_POLL_INTERVAL: 5m
kind: ConfigMap
metadata:
  name: csm-config-params
