apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dell-csm-operator-metrics-reader
  namespace: dell-csm-operator
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
