apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: application-mobility
  namespace: application-mobility
spec:
  modules:
    # Application Mobility: enable csm-application-mobility module
    - name: application-mobility
      # enable: Enable/Disable app-mobility controller
      enabled: true
      configVersion: v0.3.0
      forceRemoveModule: true
      components:
      - name: application-mobility-controller-manager
        # enable: Enable/Disable application mobility controller-manager
        enabled: true
        image: dellemc/csm-application-mobility-controller:v0.3.0
        imagePullPolicy: IfNotPresent
        envs:
          # Replica count for application mobility
          # Allowed values: string
          # Default value: 1
          - name: "APPLICATION_MOBILITY_REPLICA_COUNT"
            value: "1"

          # License for application mobility
          # Default value: license
          - name: "APPLICATION_MOBILITY_LICENSE_NAME"
            value: "license"

          # Storage-service ingress configuration
          # Default value: velero-restic-credentials
          - name: "APPLICATION_MOBILITY_OBJECT_STORE_SECRET_NAME"
            value: "velero-restic-credentials" 

      # enabled: Enable/Disable cert-manager
      # Allowed values:
      #   true: enable deployment of cert-manager
      #   false: disable deployment of cert-manager only if it's already deployed
      # Default value: false
      - name: cert-manager
        enabled: true
      # Allowed values:
      #   true: enable deployment of cert-manager
      #   false: disable deployment of cert-manager only if it's already deployed
      # Default value: false
      - name: velero
        #existingSecret: existing_secret_name 
        image: velero/velero:v1.8.1
        imagePullPolicy: IfNotPresent
        enabled: true
        features:
        - use-volume-snapshots: false
          cleanUpCRDs: false
        # enabled: Enable/Disable Velero and Restic Services
        #deployRestic: false
        #initContainers:
        #  - name: dell-custom-velero-plugin
        #    image: dellemc/csm-application-mobility-velero-plugin:v0.1.0
        #    volumeMounts:
        #    - mountPath: /target
         #     name: plugins
        # - name: velero-plugin-for-aws
        #   image: velero/velero-plugin-for-aws:v1.5.0
        #   volumeMounts:
        #    - mountPath: /target
        #      name: plugins  
        envs:
          # Backup storage location name
          # Allowed values: string
          # Default value: default
          - name: "BACKUPSTORAGELOCATION_NAME"
            value: "default"

          # Namespace for Velero installation
          # Default value: application-mobility
          - name: "VELERO_NAMESPACE"
            value: "application-mobility"

          # Based on the objectstore being used , the velero plugin and its configuration may need to change!
          # GCP and Azure plugins configuration are different. See more details at: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/README.md
          # Sample value: aws
          - name: "CONFIG_PROVIDER"
            value: "aws"

          # name to be used for secret that will be created to hold object store credentials. Used in conjunction with secretContents
          # Default value: cloud-creds
          - name: "CREDENTIAL_NAME"
            value: "cloud-creds"

          # name is the name of the volume snapshot location where snapshots are being taken. Required.
          # Volume-snapshot-Location Provider will be CONFIG_PROVIDER
          # Default value : default
          - name: "<VOL_SNAPSHOT_LOCATION_NAME>"
            value: "default"
