apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: application-mobility-controller-manager-metrics-service
  namespace: <NAMESPACE>
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <NAMESPACE>-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
