# Copyright © 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
subjects:
  - kind: ServiceAccount
    name: csipowermax-reverseproxy
    namespace: <DriverDefaultReleaseNamespace>
roleRef:
  kind: Role
  name: csipowermax-reverseproxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
spec:
  ports:
    - port: <X_CSI_REVPROXY_PORT>
      protocol: TCP
      targetPort: 2222
  selector:
    name: csipowermax-reverseproxy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csipowermax-reverseproxy
  template:
    metadata:
      labels:
        name: csipowermax-reverseproxy
    spec:
      serviceAccountName: csipowermax-reverseproxy
      containers:
        - name: csipowermax-reverseproxy
          # Replace this with the built image name
          image: <REVERSEPROXY_PROXY_SERVER_IMAGE>
          imagePullPolicy: Always
          env:
            - name: X_CSI_REVPROXY_CONFIG_DIR
              value: /etc/config/configmap
            - name: X_CSI_REVPROXY_CONFIG_FILE_NAME
              value: config.yaml
            - name: X_CSI_REVRPOXY_IN_CLUSTER
              value: "true"
            - name: X_CSI_REVPROXY_TLS_CERT_DIR
              value: /app/tls
            - name: X_CSI_REVPROXY_WATCH_NAMESPACE
              value: <DriverDefaultReleaseNamespace> #Change this to the namespace where proxy will be installed
          volumeMounts:
            - name: configmap-volume
              mountPath: /etc/config/configmap
            - name: tls-secret
              mountPath: /app/tls
            - name: cert-dir
              mountPath: /app/certs
      volumes:
        - name: configmap-volume
          configMap:
            name: <X_CSI_CONFIG_MAP_NAME>
            optional: true
        - name: tls-secret
          secret:
            secretName: <X_CSI_REVPROXY_TLS_SECRET>
        - name: cert-dir
          emptyDir:
