apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: <OBSERVABILITY_SECRET_PREFIX>-secret
  namespace: <CSM_NAMESPACE>
data:
  # replace with actual base64-encoded certificate
  tls.crt: <BASE64_CERTIFICATE>
  # replace with actual base64-encoded private key
  tls.key: <BASE64_PRIVATE_KEY>
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: <OBSERVABILITY_SECRET_PREFIX>-issuer
  namespace: <CSM_NAMESPACE>
spec:
  ca:
    secretName: <OBSERVABILITY_SECRET_PREFIX>-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <OBSERVABILITY_SECRET_PREFIX>
  namespace: <CSM_NAMESPACE>
spec:
  secretName: <OBSERVABILITY_SECRET_PREFIX>-tls
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
      - dell
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - <OBSERVABILITY_SECRET_PREFIX>
    - <OBSERVABILITY_SECRET_PREFIX>.karavi.svc.kubernetes.local
  issuerRef:
    name: <OBSERVABILITY_SECRET_PREFIX>-issuer
    kind: Issuer
    group: cert-manager.io
