apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: application-mobility-velero-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-mobility-velero-server
subjects:
  - kind: ServiceAccount
    name: dell-csm-operator-manager-service-account
    namespace: dell-csm-operator
