# permissions for end users to view containerstoragemodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerstoragemodule-viewer-role
rules:
  - apiGroups:
      - storage.dell.com
    resources:
      - containerstoragemodules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.dell.com
    resources:
      - containerstoragemodules/status
    verbs:
      - get
