# permissions for end users to view csms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csm-viewer-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csms/status
  verbs:
  - get
