apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powermax
  namespace: powermax
spec:
  driver:
    csiDriverType: "powermax"
    configVersion: v2.15.1
    forceRemoveDriver: true
    common:
      envs:
        - name: "X_CSI_REVPROXY_USE_SECRET"
          value: "false"
        - name: X_CSI_MANAGED_ARRAYS
          value: "000000000001,000000000002"
        - name: X_CSI_POWERMAX_PORTGROUPS
          value: ""
        - name: X_CSI_TRANSPORT_PROTOCOL
          value: ""
      image: quay.io/dell/container-storage-modules/csi-powermax:v2.15.1
  # These are the modules which are optional and can be enabled by specifying to enable/disable.
  modules:
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      # For Auth 2.0, use v2.2.0 as configVersion
      configVersion: v2.3.0
      components:
        - name: karavi-authorization-proxy
          envs:
            # proxyHost: hostname of the csm-authorization server
            - name: "PROXY_HOST"
              value: "authorization-ingress-nginx-controller.authorization.svc.cluster.local"
    - name: resiliency
      enabled: false
    - name: replication
      enabled: false
    - name: observability
      # enabled: Enable/Disable observability
      enabled: false
      components:
        - name: otel-collector
          enabled: true
        - name: cert-manager
          # enabled: Enable/Disable cert-manager
          # Allowed values:
          #   true: enable deployment of cert-manager
          #   false: disable deployment of cert-manager only if it's already deployed
          # Default value: false
          enabled: false
        - name: metrics-powermax
          enabled: true
