apiVersion: v1
kind: Deployment
metadata:
  name: deployment

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account

---

apiVersion: v1
kind: ClusterRole
metadata:
  name: cluster-role
  
---

apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
