apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: isilon
  namespace: isilon
spec:
  version: v1.16.0
  driver:
    csiDriverType: "isilon"
    forceRemoveDriver: true
  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      components:
        - name: karavi-authorization-proxy
          envs:
            # proxyHost: hostname of the csm-authorization server
            - name: "PROXY_HOST"
              value: "authorization-ingress-nginx-controller.authorization.svc.cluster.local"
    - name: resiliency
      # enabled: Enable/Disable Resiliency feature
      # Allowed values:
      #   true: enable Resiliency feature(deploy podmon sidecar)
      #   false: disable Resiliency feature(do not deploy podmon sidecar)
      # Default value: false
      enabled: false
    - name: replication
      enabled: false
    - name: observability
      # enabled: Enable/Disable observability
      enabled: false
      components:
        - name: otel-collector
          enabled: true
        - name: cert-manager
          # enabled: Enable/Disable cert-manager
          # Allowed values:
          #   true: enable deployment of cert-manager
          #   false: disable deployment of cert-manager only if it's already deployed
          # Default value: false
          enabled: false
        - name: metrics-powerscale
          enabled: true
