apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE>
spec:
  replicas: <APPLICATION_MOBILITY_REPLICA_COUNT>
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --app-mobility-namespace=<NAMESPACE>
        - --secret-name=<APPLICATION_MOBILITY_OBJECT_STORE_SECRET_NAME>
        - --license-name=<APPLICATION_MOBILITY_LICENSE_NAME>
        command:
        - /manager
        image: <CONTROLLER_IMAGE>
        imagePullPolicy: <CONTROLLER_IMAGE_PULLPOLICY>
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: <NAMESPACE>-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE> 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: <NAMESPACE>-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups: 
  - mobility.storage.dell.com
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - clusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - clusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - backups/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - velero.io
  resources:
  - backupstoragelocations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups/finalizers
  verbs:
  - update
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - podvolumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - resticrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volumegroup.storage.dell.com
  resources:
  - dellcsivolumegroupsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <NAMESPACE>-leader-election-role
  namespace: application-mobility
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <NAMESPACE>-manager-role
subjects:
- kind: ServiceAccount
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: <NAMESPACE>-manager-role
  namespace:  <NAMESPACE>
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <NAMESPACE>-leader-election-rolebinding
  namespace: <NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <NAMESPACE>-leader-election-role
subjects:
- kind: ServiceAccount
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <NAMESPACE>-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <NAMESPACE>-proxy-role
subjects:
- kind: ServiceAccount
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE>
---
apiVersion: v1
data:
  controller_manager_config.yaml: "apiVersion: controller-runtime.sigs.k8s.io/v1alpha1\r\nkind: ControllerManagerConfig\r\nhealth:\r\n  healthProbeBindAddress: :8081\r\nmetrics:\r\n  bindAddress: 127.0.0.1:8080\r\nwebhook:\r\n  port: 9443\r\nleaderElection:\r\n  leaderElect: true\r\n  resourceName: 50a66265.storage.dell.com\r\n"
kind: ConfigMap
metadata:
  name: <NAMESPACE>-manager-config
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <NAMESPACE>-manager-rolebinding
  namespace: <NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <NAMESPACE>-manager-role
subjects:
- kind: ServiceAccount
  name: <NAMESPACE>-controller-manager
  namespace: <NAMESPACE>
