apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
  secretName: webhook-server-cert