apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: <VELERO_NAMESPACE>
  labels:
    app.kubernetes.io/name: application-mobility-velero
    app.kubernetes.io/instance: application-mobility
spec:
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      labels:
        name: node-agent
        app.kubernetes.io/name: application-mobility-velero
        app.kubernetes.io/instance: application-mobility
    spec:
      serviceAccountName: application-mobility-velero-server-service-account
      #terminationGracePeriodSeconds: 3600
      volumes:
        - name: cloud-credentials
          secret:
            secretName: <VELERO_ACCESS>
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: scratch
          emptyDir: {}
     #dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
      containers:
        - name: node-agent
          image: <VELERO_IMAGE>
          imagePullPolicy: <VELERO_IMAGE_PULLPOLICY>
          command:
            - /velero
          args:
            - node-agent
            - server
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: scratch
              mountPath: /scratch
          env:
            - name: <VELERO_NAMESPACE>
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 1000m
              memory: 1028Mi
            limits:
              cpu: 2000m
              memory: 2024Mi
---
