apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: <BSL_NAME>
  namespace: <NAMESPACE>
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: Velero
    app.kubernetes.io/instance: 
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider: <SPEC_PROVIDER>
  default: 
  accessMode: <SPEC_ACCESS_MODE>
  objectStorage:
    bucket: <BUCKET_NAME>
    prefix: <BUCKET_PREFIX>

    caCert: <CA_CERT>
  config:
{{- range $key, $value := . }}
{{- $key | nindent 4 }}: {{ $value | quote }}

