apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: <VOL_SNAPSHOT_LOCATION_NAME>
  namespace: <VELERO_NAMESPACE>
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility

spec:
  provider: <CONFIGURATION_PROVIDER>
  config: 
      region: minio
      s3ForcePathStyle: true
      s3Url: <BACKUP_STORAGE_URL> 