apiVersion: v1
kind: Service
metadata:
  name: velero
  namespace: <NAMESPACE>
  annotations: <METRIC_SERVICE_ANNOTATIONs>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http-monitoring
      port: 8085
      targetPort: http-monitoring
  selector:
    name: velero
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
---
  apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-<SERVICE_ACCOUNT_NAME>
  namespace: <NAMESPACE>
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: <NAMESPACE>
  annotations: <SERVICE_MONITOR_ANNOTATIONS>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  namespaceSelector:
    matchNames:
      - <NAMESPACE>
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: application-mobility
  endpoints:
  - port: http-monitoring
    interval: <METRICS_SCRAPEINTERVAL>
    scrapeTimeout: <METRICS_SCRAPETIMEOUT>
    scheme: <SERVICEMONITOR_SCHEME>
    tlsConfig: <SERVICEMONITOR_TLSCONFIG>
