apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-config-map
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data: <CONFIGMAP_DATA>
