apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: application-mobility-velero-server
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: application-mobility-velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"