apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-<SERVICE_ACCOUNT_NAME>
  namespace: <NAMESPACE>
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}