apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-schedule
  namespace: <NAMESPACE>
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  useOwnerReferencesInBackup: false
  schedule: <SCHEDULE>
  template: <SCHEDULE_TEMPLATE>