apiVersion: v1
kind: Service
metadata:
  name: velero
  namespace: <NAMESPACE>
  annotations: <METRIC_SERVICE_ANNOTATIONs>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http-monitoring
      port: 8085
      targetPort: http-monitoring
  selector:
    name: velero
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility