{{- if and .Values.credentials.useSecret (not .Values.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: <CRED_EXISATING_SECRET>
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
<SECRET_CONTENTS>
<EXTRA_ENVS>