apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: velero
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  groups:
  - name: velero
    rules:
