apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    namespace: <NAMESPACE>
    name: <SERVICE_ACCOUNT_NAME>
roleRef:
  kind: ClusterRole
  name: <RBAC_CLUSTERADMINISTRATOR_NAME>
  apiGroup: rbac.authorization.k8s.io
