apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: <NAMESPACE>
  annotations: <SERVICE_MONITOR_ANNOTATIONS>
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  namespaceSelector:
    matchNames:
      - <NAMESPACE>
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: application-mobility
  endpoints:
  - port: http-monitoring
    interval: <METRICS_SCRAPEINTERVAL>
    scrapeTimeout: <METRICS_SCRAPETIMEOUT>
    scheme: <SERVICEMONITOR_SCHEME>
    tlsConfig: <SERVICEMONITOR_TLSCONFIG>

