apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: <VOL_SNAPSHOT_LOCATION_NAME>
  namespace: <VELERO_NAMESPACE>
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: application-mobility

spec:
  provider: <VOL_SNAPSHOTLOCATION_PROVIDER>
  config: 



