general:
  vulnerabilities:
    # list of CVEs that are currently unfixed
    - CVE-2022-42898
    - CVE-2022-47629 # this will be removed with the libskba library is updated in the UBI image
    - CVE-2019-1010022
    - CVE-2023-0286
    - CVE-2023-4911 # this will be removed with the glibc library is updated in the UBI image
    - CVE-2024-2961 # Another unfixed glibc CVE

  bestPracticeViolations:
    # list of best practies violatied that needs a fix
    - CIS-DI-0009 
    - DKL-DI-0006
    - CIS-DI-0005
    - CIS-DI-0006
    - CIS-DI-0008
    - DKL-LI-0003
    
