apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dell-csm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ContainerStorageModule is the Schema for the containerstoragemodules
        API
      displayName: Container Storage Module
      kind: ContainerStorageModule
      name: containerstoragemodules.storage.dell.com
      specDescriptors:
      - description: AuthSecret is the name of the credentials secret for the driver
        displayName: Auth Secret
        path: driver.authSecret
      - description: Common is the common specification for both controller and node
          plugins
        displayName: Common specification
        path: driver.common
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: driver.common.args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: driver.common.enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: driver.common.envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: driver.common.image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: driver.common.imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: driver.common.name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: driver.common.nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: driver.common.tolerations
      - description: ConfigVersion is the configuration version of the driver
        displayName: Config Version
        path: driver.configVersion
      - description: Controller is the specification for Controller plugin only
        displayName: Controller Specification
        path: driver.controller
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: driver.controller.args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: driver.controller.enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: driver.controller.envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: driver.controller.image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: driver.controller.imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: driver.controller.name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: driver.controller.nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: driver.controller.tolerations
      - description: CSIDriverType is the CSI Driver type for Dell EMC - e.g, powermax,
          powerflex,...
        displayName: CSI Driver Type
        path: driver.csiDriverType
      - description: DNSPolicy is the dnsPolicy of the daemonset for Node plugin
        displayName: DNSPolicy
        path: driver.dnsPolicy
      - description: ForceRemoveDriver is the boolean flag used to remove driver deployment
          when CR is deleted
        displayName: Force Remove Driver
        path: driver.forceRemoveDriver
      - description: ForceUpdate is the boolean flag used to force an update of the
          driver instance
        displayName: Force update
        path: driver.forceUpdate
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: driver.initContainers[0].args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: driver.initContainers[0].enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: driver.initContainers[0].envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: driver.initContainers[0].image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: driver.initContainers[0].imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: driver.initContainers[0].name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: driver.initContainers[0].nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: driver.initContainers[0].tolerations
      - description: Node is the specification for Node plugin only
        displayName: Node specification
        path: driver.node
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: driver.node.args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: driver.node.enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: driver.node.envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: driver.node.image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: driver.node.imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: driver.node.name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: driver.node.nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: driver.node.tolerations
      - description: Replicas is the count of controllers for Controller plugin
        displayName: Controller count
        path: driver.replicas
      - description: SideCars is the specification for CSI sidecar containers
        displayName: CSI SideCars specification
        path: driver.sideCars
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: driver.sideCars[0].args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: driver.sideCars[0].enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: driver.sideCars[0].envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: driver.sideCars[0].image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: driver.sideCars[0].imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: driver.sideCars[0].name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: driver.sideCars[0].nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: driver.sideCars[0].tolerations
      - description: SnapshotClass is the specification for Snapshot Classes
        displayName: Snapshot Classes
        path: driver.snapshotClass
      - description: Name is the name of the Snapshot Class
        displayName: Snapshot Class Name
        path: driver.snapshotClass[0].name
      - description: Parameters is a map of driver specific parameters for snapshot
          class
        displayName: Snapshot Class Parameters
        path: driver.snapshotClass[0].parameters
      - description: TLSCertSecret is the name of the TLS Cert secret
        displayName: TLSCert Secret
        path: driver.tlsCertSecret
      - description: Components is the specification for SM components containers
        displayName: ContainerStorageModule components specification
        path: modules[0].components
      - description: Args is the set of arguments for the container
        displayName: Container Arguments
        path: modules[0].components[0].args
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: modules[0].components[0].enabled
      - description: Envs is the set of environment variables for the container
        displayName: Container Environment vars
        path: modules[0].components[0].envs
      - description: Image is the image tag for the Container
        displayName: Container Image
        path: modules[0].components[0].image
      - description: ImagePullPolicy is the image pull policy for the image
        displayName: Container Image Pull Policy
        path: modules[0].components[0].imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name is the name of Container
        displayName: Container Name
        path: modules[0].components[0].name
      - description: NodeSelector is a selector which must be true for the pod to
          fit on a node. Selector which must match a node's labels for the pod to
          be scheduled on that node.
        displayName: NodeSelector
        path: modules[0].components[0].nodeSelector
      - description: Tolerations is the list of tolerations for the driver pods
        displayName: Tolerations
        path: modules[0].components[0].tolerations
      - description: ConfigVersion is the configuration version of the driver
        displayName: Config Version
        path: modules[0].configVersion
      - description: Enabled is used to indicate wether or not to deploy a module
        displayName: Enabled
        path: modules[0].enabled
      - description: Name is name of ContainerStorageModule modules
        displayName: Name
        path: modules[0].name
      statusDescriptors:
      - description: ControllerStatus is the status of Controller pods
        displayName: ControllerStatus
        path: controllerStatus
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: NodeStatus is the status of Controller pods
        displayName: NodeStatus
        path: nodeStatus
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: State is the state of the driver installation
        displayName: State
        path: state
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1alpha1
  description: Common Operator for installing various Dell CSI Drivers and Dell CSM
    Modules
  displayName: dell-csm-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Dell CSM Operator
  - Dell CSI Driver
  - Dell CSM Modules
  - Powerscale
  - Authorization
  links:
  - name: Dell Csm Operator
    url: https://dell-csm-operator.domain
  maintainers:
  - email: dell.csm.operator@dell.com
    name: Dell CSM Operator
  maturity: alpha
  provider:
    name: Dell Inc.
    url: https://github.com/dell/csm-operator
  version: 0.0.0
