apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: karavi
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <OBSERVABILITY-COMPONENT>
  namespace: karavi
spec:
  secretName: <OBSERVABILITY-COMPONENT>-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - dell
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - <OBSERVABILITY-COMPONENT>
  - <OBSERVABILITY-COMPONENT>.karavi.svc.kubernetes.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
