apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: test-powerstore
  namespace: test-powerstore
spec:
  driver:
    csiDriverType: "powerstore"
    # Config version for CSI PowerStore v2.0 driver
    configVersion: v2.0.0

    # volumeNamePrefix: defines a string prepended to each volume created by the CSI driver.
    # Allowed values: string
    # Default value: None
    volumeNamePrefix: csivol
    
    # controllerCount: defines the number of csi-powerscale controller pods to deploy to
    # the Kubernetes release.
    # Allowed values: n, where n > 0
    # Default value: None
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    common:
      # Image for CSI PowerStore driver v2.0
      image: "dellemc/csi-powerstore:v2.0.0"

      # imagePullPolicy: Policy to determine if the image should be pulled prior to starting the container.
      # Allowed values:
      #  Always: Always pull the image.
      #  IfNotPresent: Only pull the image if it does not already exist on the node.
      #  Never: Never pull the image.
      # Default value: None
      imagePullPolicy: IfNotPresent
      envs:
        # nodeNamePrefix: defines a string prepended to each node registered by the CSI driver.
        # Allowed values: string
        # Default value: None
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi"
        
        # nodeFCPortsFilterFile: It is the name of the environment variable which store path to the file which
        # provide list of WWPN which should be used by the driver for FC connection on this node
        # If file not exist or empty or in invalid format, then the driver will use all available FC ports
        # Allowed Values: string
        # Default Value: None
        # Example:
        # content of the file:
        #   21:00:00:29:ff:48:9f:6e,21:00:00:29:ff:48:9f:6e
        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
          value: "/etc/fc-ports-filter"
  
        # CSI driver log level
        # Allowed values: "error", "warn"/"warning", "info", "debug"
        # Default value: "debug"
        - name: "CSI_LOG_LEVEL"
          value: "debug"
        
        # CSI driver log format
        # Allowed values: "TEXT" or "JSON"
        # Default value: "TEXT"
        - name: "CSI_LOG_FORMAT"
          value: "JSON"
    node:
      envs:
        # Set to "true" to enable ISCSI CHAP Authentication
        # CHAP password will be autogenerated by driver
        - name: "X_CSI_POWERSTORE_ENABLE_CHAP"
          value: "true"

  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      configVersion: v2.0.0
      components:
      - image: dellemc/csm-authorization-sidecar:v1.0.0
        envs:
          # proxyHost: hostname of the csm-authorization server
          - name: "PROXY_HOST"
            value: ""
        
          # insecure: Enable/Disable certificate validation of the csm-authorization server       
          - name: "INSECURE"
            value: true
    
    # ContainerStorageModule module attributes
    # Set this to true to enable replication
    # Replication CRDs must be installed before installing driver
    - name: replication
      # Allowed values:
      #   "true" - replication is enabled
      #   "false" - replication is disabled
      # Default value: "false"
      enabled: false
      configVersion: v2.0.0
      components:
      - image: dellemc/dell-csi-replicator:v1.0.0
        envs:
          # replicationContextPrefix: prefix to use for naming of resources created by replication feature
          # Allowed values: string
          # Default value: powerstore
          - name: "X_CSI_REPLICATION_CONTEXT_PREFIX"
            value: powerstore
          
          # replicationPrefix: Determine if replication is enabled
          # Default value: "replication.storage.dell.com"
          # Examples: "replication.storage.dell.com", "rdf.storage.dell.com"  
          - name: "X_CSI_REPLICATION_PREFIX"
            value: "replication.storage.dell.com"
    
    # Observability
    - name: observability
      enabled: false
      configVersion: v2.0.0
      components:
      - name: CSMTopology
        image: dellemc/csm-topology:v1.0.0
        enabled: true
        envs:
          - name: "SERVICE_TYPE"
            value: ClusterIP
          #! comma separated list of provisioner names (ex: csi-vxflexos.dellemc.com)
          - name: "PROVISIONER_NAMES"
            value: "csi-vxflexos.dellemc.com,csi-powerstore.dellemc.com"
          - name: "ZIPKIN_URI"
            value: ""
          - name: "ZIPKIN_SERVICE_NAME"
            value: karavi-topology
          - name: "ZIPKIN_PROBABILITY"
            value: 0.0
          - name: "LOG_LEVEL"
            value: "INFO"
          - name: "LOG_FORMAT"
            value: "text"

      - name: CSMMetricsPowerstore
        image: dellemc/csm-metrics-powerstore:v1.0.0
        enabled: true
        envs:
          - name: "SERVICE_TYPE"
            value: ClusterIP
          
          # set the default endpoint for PowerStore service
          - name: "ENDPOINT"
            value: karavi-metrics-powerstore
          - name: "COLLECTOR_ADDR"
            value: otel-collector:55680
          - name: "PROVISIONER_NAMES"
            value: csi-powerstore.dellemc.com
          
           # set volumeMetricsEnabled to "false" to disable collection of Volume metrics
          - name: "POWERSTORE_VOLUME_METRICS_ENABLED"
            value: true

           # set polling frequency to the PowerStore array to get metrics data
          - name: "POWERSTORE_VOLUME_IO_POLL_FREQUENCY"
            value: 20
          - name: "POWERSTORE_SPACE_POLL_FREQUENCY"
            value: 300
          - name: "POWERSTORE_ARRAY_POLL_FREQUENCY"
            value: 300
          - name: "POWERSTORE_FILE_SYSTEM_POLL_FREQUENCY"
            value: 20
          
          # set the the default max concurrent queries to PowerStore
          - name: "POWERSTORE_MAX_CONCURRENT_QUERIES"
            value: 10
          - name: "ZIPKIN_URI"
            value: ""
          - name: "ZIPKIN_SERVICE_NAME"
            value: metrics-powerstore
          - name: "ZIPKIN_PROBABILITY"
            value: 0.0
          - name: "LOG_LEVEL"
            value: "INFO"
          - name: "LOG_FORMAT"
            value: "text"

      - name: otelCollector
        image: otel/opentelemetry-collector:0.9.0
        enabled: true
        envs:
          - name: "SERVICE_TYPE"
            value: ClusterIP
          - name: "NGINX_PROXY_IMAGE"
            value: "nginxinc/nginx-unprivileged:1.18"
      
      - name: certManager
        envs:
          - name: "STARTUP_API_CHECK_ENABLED"
            value:  false
          - name: "SERVICE_ACCOUNT_CREATE"
            value: false