apiVersion:  storage.dell.com/v1
kind: CSM
metadata:
  name: test-powermax
  namespace: test-powermax
spec:
  driver:
    csiDriverType: "powermax"
    k8sVersion: v1.22
    
    # "volumeNamePrefix" defines a string prepended to each volume created by the CSI driver.
    volumeNamePrefix: pmax
    
    # Config version for CSI PowerMax v2.0.0 driver
    configVersion: v2.0.0
    
    # replica: Define the number of PowerMax controller nodes
    # to deploy to the Kubernetes release
    # Allowed values: n, where n > 0
    # Default value: None
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    
    # openshift tells the operator that the installation is being done on a Red Hat OpenShift cluster
    # Don't modify this value as this value is overridden by the api controller
    isOpenshift: false
  
    common:
      # Image for CSI PowerMax driver v2.0.0
      image: dellemc/csi-powermax:v2.0.0
      # imagePullPolicy: Policy to determine if the image should be pulled prior to starting the container.
      # Allowed values:
      #  Always: Always pull the image.
      #  IfNotPresent: Only pull the image if it does not already exist on the node.
      #  Never: Never pull the image.
      # Default value: None
      imagePullPolicy: IfNotPresent
      envs:
        # X_CSI_MANAGED_ARRAYS: Serial ID of the arrays that will be used for provisioning
        # Default value: None
        # Examples: "000000000001", "000000000002"
        - name: X_CSI_MANAGED_ARRAYS
          value: "000000000000,000000000001"
        
        # X_CSI_POWERMAX_ENDPOINT: Address of the Unisphere server that is managing the PowerMax arrays
        # Default value: None
        # Example: https://0.0.0.1:8443
        - name: X_CSI_POWERMAX_ENDPOINT
          value: "https://0.0.0.0:8443/"
        
        # X_CSI_K8S_CLUSTER_PREFIX: Define a prefix that is appended onto
        # all resources created in the Array
        # This should be unique per K8s/CSI deployment
        # maximum length of this value is 3 characters
        # Default value: None
        # Examples: "XYZ", "EMC"
        - name: X_CSI_K8S_CLUSTER_PREFIX
          value: "XYZ"
        
        # X_CSI_POWERMAX_PORTGROUPS: Define the set of existing port groups that the driver will use.
        # It is a comma separated list of portgroup names.
        # Required only in case of iSCSI port groups
        # Allowed values: iSCSI Port Group names
        # Default value: None
        # Examples: "pg1", "pg1, pg2"
        - name: "X_CSI_POWERMAX_PORTGROUPS"
          value: ""
        
        # "X_CSI_TRANSPORT_PROTOCOL" can be "FC" or "FIBRE" for fibrechannel,
        # "ISCSI" for iSCSI, or "" for autoselection.
        # Allowed values:
        #   "FC"    - Fiber Channel protocol
        #   "FIBER" - Fiber Channel protocol
        #   "ISCSI" - iSCSI protocol
        #   ""      - Automatic selection of transport protocol
        # Default value: "" <empty>
        - name: "X_CSI_TRANSPORT_PROTOCOL"
          value: ""
        
        # X_CSI_POWERMAX_PROXY_SERVICE_NAME: Refers to the name of the proxy service in kubernetes
        # Set this to "powermax-reverseproxy" if you are installing the proxy
        # Allowed values: "powermax-reverseproxy"
        # default values: "" <empty>
        - name: "X_CSI_POWERMAX_PROXY_SERVICE_NAME"
          value: ""
        
        # X_CSI_GRPC_MAX_THREADS: Defines the maximum number of concurrent grpc requests.
        # Set this value to a higher number (max 50) if you are using the proxy
        # Allowed values: n, where n > 4
        # default values: None
        - name: "X_CSI_GRPC_MAX_THREADS"
          value: "4"
        
        # "skipCertificateValidation" determines if driver is going to skip verification
        # of TLS certificates while connecting to Unisphere RESTAPI interface
        # If it is set to false,
        # then a secret powermax-certs has to be created with a X.509 certificate of CA
        # which signed the Unisphere certificate
        # Allowed values:
        #   "true"  - TLS certificates verification will be skipped
        #   "false" - TLS certificates will be verified
        # Default value: "true"
        - name: "SKIP_CERTIFICATE_VALIDATION"
          value: "true"

        # "powerMaxDebug" enables low level and http traffic logging
        # between the CSI driver and Unisphere.
        # Do not enable this unless asked to do so by the support team.
        # Allowed values:
        #   "true"  - Traffic between the CSI driver and Unisphere is logged
        #   "false" - Traffic between the CSI driver and Unisphere will not be logged
        # Default value: "false"
        - name: "POWERMAX_DEBUG"
          value: "false"
        
        # CSI driver log level
        # Allowed values: "error", "warn"/"warning", "info", "debug"
        # Default value: "debug"
        - name: "CSI_LOG_LEVEL"
          value: "debug"
        
        # CSI driver log format
        # Allowed values: "TEXT" or "JSON"
        # Default value: "TEXT"
        - name: "CSI_LOG_FORMAT"
          value: "JSON"
 
    node:
      envs:
        # X_CSI_POWERMAX_ISCSI_ENABLE_CHAP: Determine if the driver is going to configure
        # ISCSI node databases on the nodes with the CHAP credentials
        # If enabled, the CHAP secret must be provided in the credentials secret
        # and set to the key "chapsecret"
        # Allowed values:
        #   "true"  - CHAP is enabled
        #   "false" - CHAP is disabled
        # Default value: "false"
        - name: "X_CSI_POWERMAX_ISCSI_ENABLE_CHAP"
          value: "false"
         
  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      configVersion: v2.0.0
      components:
      - image: dellemc/csm-authorization-sidecar:v1.0.0
        envs:
          # proxyHost: hostname of the csm-authorization server
          - name: "PROXY_HOST"
            value: ""
        
          # insecure: Enable/Disable certificate validation of the csm-authorization server       
          - name: "INSECURE"
            value: true

    # CSM module attributes
    # Set this to true to enable replication
    # Replication CRDs must be installed before installing driver
    - name: replication
      # Allowed values:
      #   "true" - replication is enabled
      #   "false" - replication is disabled
      # Default value: "false"
      enabled: false
      configVersion: v2.0.0
      components:
      - image: dellemc/dell-csi-replicator:v1.0.0
        envs:
          # replicationContextPrefix enables side cars to read
          # required information from the volume context
          # Default value: "powermax"
          # Examples: "powermax-replication", "replication"
          - name: "X_CSI_REPLICATION_CONTEXT_PREFIX"
            value: powermax
          
          # replicationPrefix: Determine if replication is enabled
          # Default value: "replication.storage.dell.com"
          # Examples: "replication.storage.dell.com", "rdf.storage.dell.com"  
          - name: "X_CSI_REPLICATION_PREFIX"
            value: "replication.storage.dell.com"

    - name: "csireverseproxy" # StandAlone
      #! Set enabled to true if you want to use proxy
      enabled: false
      configVersion: v2.0.0
      revProxyConfig:
        # Mode of CSI reverse proxy - this is a standalone API
        # it doesn't belong to kubernetes cluster API
        # Default value: None
        # Example: "StandAlone"
        mode: StandAlone
        standAloneConfig:
          storageArrays:
            - storageArrayId: "000000000001"
              # Unisphere server managing the PowerMax array
              primaryURL: https://unisphere-1-addr:8443
              
              # proxyCredentialSecrets are used by the clients of the proxy to connect to it
              # If using proxy in the stand alone mode, then the driver must be provided the
              # same secret.
              # The format of the proxy credential secret are exactly the same as the unisphere credential secret
              # For using the proxy with the driver, use the same proxy credential secrets for
              # all the managed storage arrays
              proxyCredentialSecrets:
                - proxy-creds
            - storageArrayId: "000000000002"
              primaryURL: https://unisphere-2-addr:8443
              
              # An optional backup Unisphere server managing the same array
              # This can be used by the proxy to fall back to in case the primary
              # Unisphere is inaccessible temporarily
              backupURL: unisphere-3-addr:8443
              proxyCredentialSecrets:
                - proxy-creds
          managementServers:
            - url: https://unisphere-1-addr:8443
              # Secret containing the credentials of the Unisphere server
              arrayCredentialSecret: unsiphere-1-creds
              skipCertificateValidation: true
            - url: https://unisphere-2-addr:8443
              arrayCredentialSecret: unsiphere-2-creds
              skipCertificateValidation: true
            - url: https://unisphere-3-addr:8443
              arrayCredentialSecret: unsiphere-3-creds
              skipCertificateValidation: true
      components:
        # image: Define the container images used for the reverse proxy
        # Default value: None
        # Example: "csipowermax-reverseproxy:v1.4.0"
        - image: dellemc/csipowermax-reverseproxy:v1.4.0
          envs:
          # "tlsSecret" defines the TLS secret that is created with certificate
          # and its associated key
          # Default value: None
          # Example: "tls-secret"
          - name: "TLS_SECRET"
            value: "csirevproxy-tls-secret"
          
          # Set enabled to true if you want to deploy csireverseproxy as sidecar
          # Allowed values:
          #   "true"  - CSI reverse proxy will be deployed as a sidecar
          #   "false" - CSI reverse proxy will be deployed along with driver
          # Default value: "true"
          - name: "DEPLOY_AS_SIDECAR"
            value: false
          
          # Port number for csireverseproxy to listen
          # Default value: None
          # Examples: "1111", "8080"
          - name: "PORT"
            value: 2222
 
    - name: "csireverseproxy" # Linked
      #! Set enabled to true if you want to use proxy
      enabled: false
      configVersion: v2.0.0
      revProxyConfig:
        # Mode for the proxy
        # Default value: None
        # Example: "Linked"
        mode: Linked
        linkConfig:
          primary:
            url: https://0.0.0.0:8443 #Unisphere URL
            skipCertificateValidation: true # This setting determines if client side Unisphere certificate validation is to be skipped
            certSecret: "" # Provide this value if skipCertificateValidation is set to false
          backup: # This is an optional field and lets you configure a backup unisphere which can be used by proxy server
            url: https://0.0.0.0:8443 #Unisphere URL
            skipCertificateValidation: true
 
      components:
        # image: Define the container images used for the reverse proxy
        # Default value: None
        # Example: "csipowermax-reverseproxy:v1.4.0"
        - image: dellemc/csipowermax-reverseproxy:v1.4.0
          envs:
          # "tlsSecret" defines the TLS secret that is created with certificate
          # and its associated key
          # Default value: None
          # Example: "tls-secret"
          - name: "TLS_SECRET"
            value: "csirevproxy-tls-secret"
          
          # Set enabled to true if you want to deploy csireverseproxy as sidecar
          # Allowed values:
          #   "true"  - CSI reverse proxy will be deployed as a sidecar
          #   "false" - CSI reverse proxy will be deployed along with driver
          # Default value: "true"
          - name: "DEPLOY_AS_SIDECAR"
            value: true
          
          # Port number for csireverseproxy to listen
          # Default value: None
          # Examples: "1111", "8080"
          - name: "PORT"
            value: 2222
          