apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: vxflexos
  namespace: vxflexos
spec:
  driver:
    csiDriverType: "powerflex"
    configVersion: v2.12.0
    forceRemoveDriver: true
  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      # For Auth 2.0, use v2.0.0 as configVersion
      configVersion: v1.12.0
      components:
        - name: karavi-authorization-proxy
          image: quay.io/dell/container-storage-modules/csm-authorization-sidecar:v1.12.0
          envs:
            # proxyHost: hostname of the csm-authorization server
            - name: "PROXY_HOST"
              value: "authorization-ingress-nginx-controller.authorization.svc.cluster.local"
            # skipCertificateValidation: Enable/Disable certificate validation of the csm-authorization server
            - name: "SKIP_CERTIFICATE_VALIDATION"
              value: "true"
    - name: resiliency
      # enabled: Enable/Disable Resiliency feature
      # Allowed values:
      #   true: enable Resiliency feature(deploy podmon sidecar)
      #   false: disable Resiliency feature(do not deploy podmon sidecar)
      # Default value: false
      enabled: false
    - name: replication
      enabled: false
    # observability: allows to configure observability
    - name: observability
      # enabled: Enable/Disable observability
      enabled: false
      components:
        - name: topology
          enabled: true
        - name: otel-collector
          enabled: true
        - name: cert-manager
          # enabled: Enable/Disable cert-manager
          # Allowed values:
          #   true: enable deployment of cert-manager
          #   false: disable deployment of cert-manager only if it's already deployed
          # Default value: false
          enabled: false
        - name: metrics-powerflex
          enabled: true
