apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: vxflexos
  namespace: vxflexos
spec:
  driver:
    csiDriverType: "powerstore"
    configVersion: v2.11.0
    forceRemoveDriver: true