apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powermax
  namespace: powermax
spec:
  driver:
    csiDriverType: "powermax"
    configVersion: v2.12.0
# These are the modules which are optional and can be enabled by specifying to enable/disable.
  modules:
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
    - name: resiliency
      enabled: false
  
