apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powerstore
  namespace: powerstore
spec:
  driver:
    csiDriverType: "powerstore"
    configVersion: v2.14.0
    forceRemoveDriver: true
  modules:
    - name: resiliency
      # enabled: Enable/Disable Resiliency feature
      # Allowed values:
      #   true: enable Resiliency feature(deploy podmon sidecar)
      #   false: disable Resiliency feature(do not deploy podmon sidecar)
      # Default value: false
      enabled: false
  node:
    envs:
     - name: X_CSI_SDC_SFTP_REPO_ENABLED
       value: "false"
