apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powermax
  namespace: powermax
spec:
  driver:
    csiDriverType: "powermax"
    configVersion: v2.11.0
  modules:
    - name: csireverseproxy
      enabled: true
      configVersion: v2.10.0
