apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-unity.dellemc.com
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: restricted
spec:
  attachRequired: true
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  fsGroupPolicy: ReadWriteOnceWithFSType
