apiVersion: storage.dell.com/v1
kind: ApexConnectivityClient
metadata:
  name: apex-connectivity-client
  namespace: apex-connectivity-client
spec:
  client:
    csmClientType: "apexConnectivityClient"
    configVersion: v1.0.0
    connectionTarget: connect-into.dell.com
    forceRemoveClient: true
    common:
      name: connectivity-client-docker-k8s
      image: dellemc/connectivity-client-docker-k8s
      imagePullPolicy: IfNotPresent
    initContainers:
      - name: connectivity-client-init
        image: registry.access.redhat.com/ubi9/ubi-micro
        imagePullPolicy: IfNotPresent
    sideCars:
      - name: kubernetes-proxy
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
      - name: cert-persister
        image: dellemc/connectivity-cert-persister-k8s
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Secret
metadata:
  name: connectivity-client-docker-k8s-cert
  namespace: apex-connectivity-client
type: Opaque
data:
  cert.pem: ""
