apiVersion: storage.dell.com/v1
kind: ApexConnectivityClient
metadata:
  name: apex-connectivity-client
  namespace: apex-connectivity-client
spec:
  client:
    csmClientType: "apexConnectivityClient"
    configVersion: v1.0.0
    forceRemoveClient: true
    common:
      name: connectivity-client-docker-k8s
      image: "amaas-eos-mw1.cec.lab.emc.com:5106/dcm/connectivity-client-docker-k8s:1.1.3"
      imagePullPolicy: IfNotPresent
    initContainers:
      - name: apex-connectivity-client-init
        image: registry.access.redhat.com/ubi9/ubi-micro
        imagePullPolicy: Always
    sideCars:
      - name: kubernetes-proxy
        image: bitnami/kubectl:latest
        imagePullPolicy: Always
      - name: cert-persister
        image: amaas-eos-drm2.cec.lab.emc.com:5074/csm/cert-persister:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: connectivity-client-docker-k8s-cert
  namespace: apex-connectivity-client
type: Opaque
data:
  cert.pem: ""
