apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: vxflexos
  namespace: vxflexos
spec:
  driver:
    csiDriverType: "powerflex"
    csiDriverSpec:
      # in OCP <= 4.16 and K8s <= 1.29, fsGroupPolicy is an immutable field
      # fsGroupPolicy: Defines if the underlying volume supports changing ownership and permission of the volume before being mounted.
      # Allowed values: ReadWriteOnceWithFSType, File , None
      # Default value: ReadWriteOnceWithFSType
      fSGroupPolicy: "File"
      # storageCapacity: Helps the scheduler to schedule the pod on a node satisfying the topology constraints, only if the requested capacity is available on the storage array
      # Allowed values:
      #   true: enable storage capacity tracking
      #   false: disable storage capacity tracking
      storageCapacity: true
    configVersion: v2.11.0
    replicas: 1
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    forceRemoveDriver: true
    common:
      image: "dellemc/csi-vxflexos:v2.11.0"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: "false"
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: "false"
        - name: X_CSI_DEBUG
          value: "true"
        # Specify kubelet config dir path.
        # Ensure that the config.yaml file is present at this path.
        # Default value: /var/lib/kubelet
        - name: KUBELET_CONFIG_DIR
          value: "/var/lib/kubelet"
        - name: "CERT_SECRET_COUNT"
          value: "0"
        - name: X_CSI_QUOTA_ENABLED
          value: "false"
    sideCars:
      # 'k8s' represents a string prepended to each volume created by the CSI driver
      - name: provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
        args: ["--volume-name-prefix=k8s"]
      - name: attacher
        image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
      - name: registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
      - name: resizer
        image: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
      - name: snapshotter
        image: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1
      - name: csi-metadata-retriever
        image: dellemc/csi-metadata-retriever:v1.8.0
        # sdc-monitor is disabled by default, due to high CPU usage
      - name: sdc-monitor
        enabled: false
        image: dellemc/sdc:4.5.2.1
        envs:
          - name: HOST_PID
            value: "1"
          - name: MDM
            value: "10.xx.xx.xx,10.xx.xx.xx"  # do not add mdm value here if it is present in secret
            # health monitor is disabled by default, refer to driver documentation before enabling it
            # Also set the env variable controller.envs.X_CSI_HEALTH_MONITOR_ENABLED  to "true".
      - name: csi-external-health-monitor-controller
        enabled: false
        args: ["--monitor-interval=60s"]
        image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.12.1
    # Uncomment the following to configure how often external-provisioner polls the driver to detect changed capacity
    # Configure when the storageCapacity is set as "true"
    # Allowed values: 1m,2m,3m,...,10m,...,60m etc. Default value: 5m
    # - name: provisioner
    #  args: ["--capacity-poll-interval=5m"]

    controller:
      envs:
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from Controller plugin - volume condition.
        # Install the 'external-health-monitor' sidecar accordingly.
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        # X_CSI_POWERFLEX_EXTERNAL_ACCESS: Allows to specify additional entries for hostAccess of NFS volumes. Both single IP address and subnet are valid entries.
        # Allowed Values: x.x.x.x/xx or x.x.x.x
        # Default Value: None
        - name: X_CSI_POWERFLEX_EXTERNAL_ACCESS
          value:
      # "controller.nodeSelector" defines what nodes would be selected for pods of controller deployment
      # Leave as blank to use all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # "controller.tolerations" defines tolerations that would be applied to controller deployment
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"
    node:
      envs:
        # X_CSI_APPROVE_SDC_ENABLED: Enables/Disable SDC approval
        # Allowed values:
        #    true: enable SDC approval
        #    false: disable SDC approval
        # Default value: false
        - name: X_CSI_APPROVE_SDC_ENABLED
          value: "false"
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from node plugin - volume usage
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        # X_CSI_RENAME_SDC_ENABLED: Enable/Disable rename of SDC
        # Allowed values:
        #   true: enable renaming
        #   false: disable renaming
        # Default value: false
        - name: X_CSI_RENAME_SDC_ENABLED
          value: "false"
        # X_CSI_RENAME_SDC_PREFIX: defines a string for prefix of the SDC name.
        # "prefix" + "worker_node_hostname" should not exceed 31 chars.
        # Default value: none
        # Examples: "rhel-sdc", "sdc-test"
        - name: X_CSI_RENAME_SDC_PREFIX
          value: ""
        # X_CSI_MAX_VOLUMES_PER_NODE: Defines the maximum PowerFlex volumes that can be created per node
        # Allowed values: Any value greater than or equal to 0
        # If value is zero Container Orchestrator shall decide how many volumes of this type can be published by the controller to the node.
        # This limit is applicable to all the nodes in the cluster for which node label 'maxVxflexosVolumesPerNode' is not set.
        # Default value: "0"
        - name: X_CSI_MAX_VOLUMES_PER_NODE
          value: "0"
      # "node.nodeSelector" defines what nodes would be selected for pods of node daemonset
      # Leave as blank to use all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # "node.tolerations" defines tolerations that would be applied to node daemonset
      # Leave as blank to install node driver only on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"
    initContainers:
      - image: dellemc/sdc:4.5.2.1
        imagePullPolicy: IfNotPresent
        name: sdc
        envs:
          - name: MDM
            value: "10.xx.xx.xx,10.xx.xx.xx"  # provide MDM value
  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enable: Enable/Disable csm-authorization
      enabled: false
      # For PowerFlex Tech-Preview v2.0.0-alpha use v1.11.0 as configVersion.
      # Do not change the configVersion to v2.0.0-alpha
      configVersion: v1.11.0
      components:
        - name: karavi-authorization-proxy
          # Use image: dellemc/csm-authorization-sidecar:v2.0.0-alpha for PowerFlex Tech-Preview v2.0.0-alpha
          image: dellemc/csm-authorization-sidecar:v1.11.0
          envs:
            # proxyHost: hostname of the csm-authorization server
            - name: "PROXY_HOST"
              value: "csm-authorization.com"
            # skipCertificateValidation: Enable/Disable certificate validation of the csm-authorization server
            - name: "SKIP_CERTIFICATE_VALIDATION"
              value: "true"
    # observability: allows to configure observability
    - name: observability
      enabled: true
      configVersion: v1.9.0
      components:
        - name: topology
          enabled: true
        - name: otel-collector
          enabled: true
        - name: cert-manager
          enabled: false
        - name: metrics-powerflex
          enabled: true
    # Replication: allows to configure replication
    # Replication CRDs must be installed before installing driver
    - name: replication
      # enabled: Enable/Disable replication feature
      # Allowed values:
      #   true: enable replication feature(install dell-csi-replicator sidecar)
      #   false: disable replication feature(do not install dell-csi-replicator sidecar)
      # Default value: false
      enabled: false
      configVersion: v1.9.0
      components:
        - name: dell-csi-replicator
          # image: Image to use for dell-csi-replicator. This shouldn't be changed
          # Allowed values: string
          # Default value: None
          image: dellemc/dell-csi-replicator:v1.9.0
          envs:
            # replicationPrefix: prefix to prepend to storage classes parameters
            # Allowed values: string
            # Default value: replication.storage.dell.com
            - name: "X_CSI_REPLICATION_PREFIX"
              value: "replication.storage.dell.com"
            # replicationContextPrefix: prefix to use for naming of resources created by replication feature
            # Allowed values: string
            - name: "X_CSI_REPLICATION_CONTEXT_PREFIX"
              value: "powerflex"
        - name: dell-replication-controller-manager
          # image: Defines controller image. This shouldn't be changed
          # Allowed values: string
          image: dellemc/dell-replication-controller:v1.9.0
          envs:
            # TARGET_CLUSTERS_IDS: comma separated list of cluster IDs of the targets clusters. DO NOT include the source(wherever CSM Operator is deployed) cluster ID
            # Set the value to "self" in case of stretched/single cluster configuration
            # Allowed values: string
            - name: "TARGET_CLUSTERS_IDS"
              value: "target-cluster-1"
            # Replication log level
            # Allowed values: "error", "warn"/"warning", "info", "debug"
            # Default value: "debug"
            - name: "REPLICATION_CTRL_LOG_LEVEL"
              value: "debug"
            # replicas: Defines number of controller replicas
            # Allowed values: int
            # Default value: 1
            - name: "REPLICATION_CTRL_REPLICAS"
              value: "1"
            # retryIntervalMin: Initial retry interval of failed reconcile request.
            # It doubles with each failure, upto retry-interval-max
            # Allowed values: time
            - name: "RETRY_INTERVAL_MIN"
              value: "1s"
            # RETRY_INTERVAL_MAX: Maximum retry interval of failed reconcile request
            # Allowed values: time
            - name: "RETRY_INTERVAL_MAX"
              value: "5m"
    - name: resiliency
      # enabled: Enable/Disable Resiliency feature
      # Allowed values:
      #   true: enable Resiliency feature(deploy podmon sidecar)
      #   false: disable Resiliency feature(do not deploy podmon sidecar)
      # Default value: false
      enabled: false
      configVersion: v1.10.0
      components:
        - name: podmon-controller
          image: dellemc/podmon:v1.10.0
          imagePullPolicy: IfNotPresent
          args:
            - "--labelvalue=csi-vxflexos"
            - "--skipArrayConnectionValidation=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--arrayConnectivityPollRate=5"
            - "--arrayConnectivityConnectionLossThreshold=3"
            # Below 3 args should not be modified.
            - "--csisock=unix:/var/run/csi/csi.sock"
            - "--mode=controller"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
        - name: podmon-node
          image: dellemc/podmon:v1.10.0
          imagePullPolicy: IfNotPresent
          envs:
            # podmonAPIPort: Defines the port to be used within the kubernetes cluster
            # Allowed values: Any valid and free port (string)
            # Default value: 8083
            - name: "X_CSI_PODMON_API_PORT"
              value: "8083"
          args:
            - "--labelvalue=csi-vxflexos"
            - "--leaderelection=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--arrayConnectivityPollRate=5"
            # Below 3 args should not be modified.
            - "--csisock=unix:/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock"
            - "--mode=node"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
