# This job is meant primarily for cleaning up on CI systems.
# Using this on production systems, especially those that have multiple releases of Velero, will be destructive.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "velero.fullname" . }}-cleanup-crds
  namespace: <NAMESPACE>
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  backoffLimit: 3
  template:
    metadata:
      name: velero-cleanup-crds
      {{- with .Values.kubectl.labels }}
      labels:
      {{- with .Values.kubectl.annotations }}
      annotations:
    spec:
      imagePullSecrets:
        - name: 
      serviceAccountName: {{ include "velero.serverServiceAccount" . }}
      containers:
        - name: kubectl
          image: <KUBECTL_IMAGEREPOSITORY>@<KUBECTL_IMAGEDIGEST>
          image: <KUBECTL_IMAGEREPOSITORY>:<KUBECTL_IMAGETAG>
          image: <KUBECTL_IMAGEREPOSITORY>:{{ template "chart.KubernetesVersion" . }}"
          imagePullPolicy: <IMAGE_PULLPOLICY>
          command:
            - /bin/sh
            - -c
            - >
              kubectl delete restore --all;
              kubectl delete backup --all;
              kubectl delete backupstoragelocation --all;
              kubectl delete volumesnapshotlocation --all;
              kubectl delete podvolumerestore --all;
              kubectl delete crd -l component=velero;
          securityContext: 
          resources:
      restartPolicy: OnFailure
      {{- with $podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
