apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "velero.fullname" . }}
  namespace: <PROMETHEUS_NAMESPACE>
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  groups:
  - name: {{ include "velero.name" . }}
    rules:
