apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "velero.fullname" . }}-server
  namespace: <NMAESPACE>
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
subjects:
  - kind: ServiceAccount
    namespace: <NAMESPACE>
    name: {{ include "velero.serverServiceAccount" . }}
roleRef:
  kind: Role
  name: {{ include "velero.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
