apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "velero.fullname" . }}
  namespace: <NAMESPACE>
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  namespaceSelector:
    matchNames:
      - <NAMESPACE>
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velero.name" . }}
      app.kubernetes.io/instance: application-mobility
  endpoints:
  - port: http-monitoring
    interval: <METRICS_SCRAPEINTERVAL>
    scrapeTimeout: <METRICS_SCRAPETIMEOUT>
    scheme: <SERVICEMONITOR_SCHEME>
    tlsConfig: <SERVICEMONITOR_TLSCONFIG>

