apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: {{ include "velero.volumeSnapshotLocation.name" . }}
  namespace: <NAMESPACE>
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: <VALERO_NAME>
    app.kubernetes.io/instance: application-mobility
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  provider: {{ include "velero.volumeSnapshotLocation.provider" . }}
  config:


