apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  labels:
    app.kubernetes.io/name: csm-operator-v4
    app.kubernetes.io/managed-by: kustomize
  name: containerstoragemodule-sample
spec:
  # TODO(user): Add fields here
