apiVersion: v1
kind: ServiceAccount
metadata:
  name: karavi-metrics-powerflex-controller
  namespace: karavi

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karavi-metrics-powerflex-controller
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karavi-metrics-powerflex-controller
subjects:
  - kind: ServiceAccount
    name: karavi-metrics-powerflex-controller
    namespace: karavi
roleRef:
  kind: ClusterRole
  name: karavi-metrics-powerflex-controller
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: karavi-metrics-powerflex
    app.kubernetes.io/instance: karavi
  name: karavi-metrics-powerflex
  namespace: karavi
spec:
  type: ClusterIP
  ports:
    - name: karavi-metrics-powerflex
      port: 2222
      targetPort: 2222
  selector:
    app.kubernetes.io/name: karavi-metrics-powerflex
    app.kubernetes.io/instance: karavi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: karavi-metrics-powerflex-configmap
  namespace: karavi
data:
  karavi-metrics-powerflex.yaml : |
    COLLECTOR_ADDR: <COLLECTOR_ADDRESS>
    PROVISIONER_NAMES: csi-vxflexos.dellemc.com
    POWERFLEX_SDC_METRICS_ENABLED: <POWERFLEX_SDC_METRICS_ENABLED>
    POWERFLEX_SDC_IO_POLL_FREQUENCY: <POWERFLEX_SDC_IO_POLL_FREQUENCY>
    POWERFLEX_VOLUME_IO_POLL_FREQUENCY: <POWERFLEX_VOLUME_IO_POLL_FREQUENCY>
    POWERFLEX_VOLUME_METRICS_ENABLED: <POWERFLEX_VOLUME_METRICS_ENABLED>
    POWERFLEX_STORAGE_POOL_METRICS_ENABLED: <POWERFLEX_STORAGE_POOL_METRICS_ENABLED>
    POWERFLEX_STORAGE_POOL_POLL_FREQUENCY: <POWERFLEX_STORAGE_POOL_POLL_FREQUENCY>
    POWERFLEX_MAX_CONCURRENT_QUERIES: <POWERFLEX_MAX_CONCURRENT_QUERIES>
    LOG_LEVEL: <POWERFLEX_LOG_LEVEL>
    LOG_FORMAT: <POWERFLEX_LOG_FORMAT>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: karavi-metrics-powerflex
  namespace: karavi
  labels:
    app.kubernetes.io/name: karavi-metrics-powerflex
    app.kubernetes.io/instance: karavi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karavi-metrics-powerflex
      app.kubernetes.io/instance: karavi
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karavi-metrics-powerflex
        app.kubernetes.io/instance: karavi
    spec:
      serviceAccount: karavi-metrics-powerflex-controller
      containers:
        - name: karavi-metrics-powerflex
          image: <POWERFLEX_OBS_IMAGE>
          resources: {}
          env:
            - name: POWERFLEX_METRICS_ENDPOINT
              value: "karavi-metrics-powerflex"
            - name: POWERFLEX_METRICS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TLS_ENABLED
              value: "true"
          volumeMounts:
            - name: vxflexos-config
              mountPath: /vxflexos-config
            - name: tls-secret
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: karavi-metrics-powerflex-configmap
              mountPath: /etc/config
      volumes:
        - name: vxflexos-config
          secret:
            secretName: <DriverDefaultReleaseName>-config
        - name: tls-secret
          secret:
            secretName: otel-collector-tls
            items:
              - key: tls.crt
                path: cert.crt
        - name: karavi-metrics-powerflex-configmap
          configMap:
            name: karavi-metrics-powerflex-configmap
      restartPolicy: Always
status: {}