apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: csi-isilon.dellemc.com
spec:
    attachRequired: true
    podInfoOnMount: true
    storageCapacity: true
    fsGroupPolicy: ReadWriteOnceWithFSType
    volumeLifecycleModes:
    - Persistent
    - Ephemeral
