apiVersion: v1
kind: ServiceAccount
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <DriverDefaultReleaseName>-node
subjects:
  - kind: ServiceAccount
    name: <DriverDefaultReleaseName>-node
    namespace: <DriverDefaultReleaseNamespace>
roleRef:
  kind: ClusterRole
  name: <DriverDefaultReleaseName>-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: <DriverDefaultReleaseName>-node
  namespace: <DriverDefaultReleaseNamespace>
spec:
  selector:
    matchLabels:
      app: <DriverDefaultReleaseName>-node
  template:
    metadata:
      labels:
        app: <DriverDefaultReleaseName>-node
        csmNamespace: <CSM_NAMESPACE>
      annotations:
        kubectl.kubernetes.io/default-container: driver
    spec:
      serviceAccount: <DriverDefaultReleaseName>-node
      # nodeSelector:
      # tolerations:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: driver
          command: ["/csi-isilon"]
          args:
            - "--driver-config-params=/csi-isilon-config-params/driver-config-params.yaml"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: dellemc/csi-isilon:v2.11.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CSI_ENDPOINT
              value: <KUBELET_CONFIG_DIR>/plugins/csi-isilon/csi_sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_ISI_SKIP_CERTIFICATE_VALIDATION
              value: "true"
            - name: X_CSI_ISI_AUTH_TYPE
              value: "0"
            - name: X_CSI_ALLOWED_NETWORKS
              value: ""
            - name: X_CSI_VERBOSE
              value: "1"
            - name: X_CSI_PRIVATE_MOUNT_DIR
              value: "<KUBELET_CONFIG_DIR>/plugins/csi-isilon/disks"
            - name: X_CSI_ISI_PORT
              value: "8080"
            - name: X_CSI_ISI_PATH
              value: "/ifs/data/csi"
            - name: X_CSI_ISI_NO_PROBE_ON_START
              value: "false"
            - name: X_CSI_ISI_AUTOPROBE
              value: "true"
            - name: X_CSI_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: X_CSI_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SSL_CERT_DIR
              value: /certs
            - name: X_CSI_ISI_QUOTA_ENABLED
              value: "true"
            - name: X_CSI_CUSTOM_TOPOLOGY_ENABLED
              value: "false"
            - name: X_CSI_ISI_CONFIG_PATH
              value: /isilon-configs/config
            - name: X_CSI_MAX_VOLUMES_PER_NODE
              value: "0"
            - name: X_CSI_HEALTH_MONITOR_ENABLED
              value: "false"
            - name: X_CSI_MAX_PATH_LIMIT
              value: "192"
          volumeMounts:
            - name: driver-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/csi-isilon
            - name: volumedevices-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
            - name: csi-path
              mountPath: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi
            - name: pods-path
              mountPath: <KUBELET_CONFIG_DIR>/pods
              mountPropagation: "Bidirectional"
            - name: dev
              mountPath: /dev
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: isilon-configs
              mountPath: /isilon-configs
            - name: csi-isilon-config-params
              mountPath: /csi-isilon-config-params
        - name: registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=<KUBELET_CONFIG_DIR>/plugins/csi-isilon/csi_sock
          env:
            - name: ADDRESS
              value: /csi/csi_sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: driver-path
              mountPath: /csi
      volumes:
        - name: usr-bin
          hostPath:
            path: /usr/bin
            type: Directory
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: var-run
          hostPath:
            path: /var/run
            type: Directory
        - name: registration-dir
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins_registry/
            type: DirectoryOrCreate
        - name: csi-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi
        - name: driver-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/csi-isilon
            type: DirectoryOrCreate
        - name: volumedevices-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/plugins/kubernetes.io/csi/volumeDevices
            type: DirectoryOrCreate
        - name: pods-path
          hostPath:
            path: <KUBELET_CONFIG_DIR>/pods
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: certs
          projected:
            sources:
              - secret:
                  name: <DriverDefaultReleaseName>-certs-0
                  items:
                    - key: cert-0
                      path: cert-0
        - name: isilon-configs
          secret:
            secretName: <DriverDefaultReleaseName>-creds
        - name: csi-isilon-config-params
          configMap:
            name: <DriverDefaultReleaseName>-config-params
