apiVersion: csm-authorization.storage.dell.com/v1alpha1
kind: Storage
metadata:
  name: powerflex
spec:
  type: powerflex
  endpoint: https://127.0.0.1
  systemID: 1a99aa999999aa9a
  vault:
    identifier: vault0
    kvEngine: secret
    path: powerflex/1a99aa999999aa9a
  skipCertificateValidation: true
  pollInterval: 30s
