apiVersion: csm-authorization.storage.dell.com/v1
kind: Storage
metadata:
  name: powerflex
spec:
  type: powerflex
  endpoint: https://127.0.0.1
  systemID: 1a99aa999999aa9a
  storageSystemCredentials:
    secretProviderClass:
      name: secretProviderClassName
      usernameObjectName: ""
      passwordObjectName: ""
  skipCertificateValidation: true
  pollInterval: 30s
  isiPath: /ifs/data/csi
