apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: authorization
spec:
  modules:
    # Authorization: enable csm-authorization proxy server for RBAC
    - name: authorization-proxy-server
      # enable: Enable/Disable csm-authorization
      enabled: true
      configVersion: v1.11.0
      forceRemoveModule: true
      components:
      - name: karavi-authorization-proxy-server
        # enable: Enable/Disable csm-authorization proxy server
        enabled: true
        proxyService: dellemc/csm-authorization-proxy:v1.11.0
        tenantService: dellemc/csm-authorization-tenant:v1.11.0
        roleService: dellemc/csm-authorization-role:v1.11.0
        storageService: dellemc/csm-authorization-storage:v1.11.0
        redis: dellemc/redis:6.0.8-alpine
        commander: dellemc/redis-commander:latest
        opa: dellemc/opa
        opaKubeMgmt: dellemc/kube-mgmt:0.11
        envs:
          # proxy-server ingress will use this hostname
          # NOTE: an additional hostname can be configured in the PROXY_INGRESS_HOST environment variable
          # NOTE: proxy-server ingress is configured to accept IP address connections so hostnames are not required
          # NOTE: csm-authorization.com is a placeholder for the proxyHost. See the administrator of CSM for Authorization for the correct value
          - name: "PROXY_HOST"
            value: "csm-authorization.com"

          # Proxy-service ingress configuration
          # Default value: nginx
          - name: "PROXY_INGRESS_CLASSNAME"
            value: "nginx"
          # An additional host rule for the proxy-server ingress
          # Default value: authorization-ingress-nginx-controller.namespace.svc.cluster.local
          - name: "PROXY_INGRESS_HOST"
            value: "authorization-ingress-nginx-controller.authorization.svc.cluster.local"

          # by default, csm-authorization will deploy a local (https://kubernetes.io/docs/concepts/storage/storage-classes/#local) volume for redis
          # to use a different storage class for redis, specify the name of the storage class
          # NOTE: the storage class must NOT be a storage class provisioned by a CSI driver using this installation of CSM Authorization
          # Default value: None
          - name: "REDIS_STORAGE_CLASS"
            value: ""

      # enabled: Enable/Disable nginx ingress
      # Allowed values:
      #   true: enable deployment of nginx ingress controller
      #   false: disable deployment of nginx ingress only if you have your own ingress controller
      # Default value: true
      - name: ingress-nginx
        enabled: true

      # enabled: Enable/Disable cert-manager
      # Allowed values:
      #   true: enable deployment of cert-manager
      #   false: disable deployment of cert-manager only if it's already deployed
      # Default value: true
      - name: cert-manager
        enabled: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csm-config-params
data:
  csm-config-params.yaml: |
    CONCURRENT_POWERFLEX_REQUESTS: 10
    LOG_LEVEL: debug
