apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: vxflexos
  namespace: vxflexos
spec:
  version: v1.16.0
  driver:
    csiDriverType: "powerflex"
    csiDriverSpec:
      # in OCP <= 4.16 and K8s <= 1.29, fsGroupPolicy is an immutable field
      # fsGroupPolicy: Defines if the underlying volume supports changing ownership and permission of the volume before being mounted.
      # Allowed values: ReadWriteOnceWithFSType, File , None
      # Default value: File
      fSGroupPolicy: "File"
      # storageCapacity: Helps the scheduler to schedule the pod on a node satisfying the topology constraints, only if the requested capacity is available on the storage array
      # Allowed values:
      #   true: enable storage capacity tracking
      #   false: disable storage capacity tracking
      storageCapacity: true
    replicas: 1
    dnsPolicy: ClusterFirstWithHostNet
    forceRemoveDriver: true
    common:
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: "false"
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: "false"
        # Log level for CSI driver, passed to logrus.
        # Options are "PANIC", "FATAL", "ERROR", "WARN", "INFO",
        # "DEBUG", and "TRACE".
        - name: CSI_LOG_LEVEL
          value: "INFO"
        # GOSCALEIO_DEBUG: Enable/disable debug logs from goscaleio library.
        # Default value: false
        - name: GOSCALEIO_DEBUG
          value: "false"
        # GOSCALEIO_SHOWHTTP: Enable/disable HTTP requests and responses from goscaleio library
        - name: GOSCALEIO_SHOWHTTP
          value: "false"
        # Specify kubelet config dir path.
        # Ensure that the config.yaml file is present at this path.
        # Default value: /var/lib/kubelet
        - name: KUBELET_CONFIG_DIR
          value: "/var/lib/kubelet"
        - name: "CERT_SECRET_COUNT"
          value: "0"
        - name: X_CSI_QUOTA_ENABLED
          value: "false"
        # CSI driver interface names for NFS deployment without SDC
        # Multiple interface names should be separated by comma
        # Ensure to single quote the whole value and double quote each interface name
        # Examples: 'worker1: "interface1",worker2: "interface2"'
        # Default value: None, required only when X_CSI_SDC_ENABLED is set to false
        - name: INTERFACE_NAMES
          value:
        # X_CSI_PROBE_TIMEOUT: Specify the timeout limit for controller and node to communicate with the array.
        # Allowed values: 1s, 10s, etc.
        # In the format of a duration.
        # Default value: 10s
        - name: X_CSI_PROBE_TIMEOUT
          value: "10s"
        # X_CSI_AUTH_TYPE: Specify the authentication type to be used.
        # Allowed values: OIDC, "" empty
        - name: X_CSI_AUTH_TYPE
          value: ""
    sideCars:
      # 'csivol' represents a string prepended to each volume created by the CSI driver
      - name: provisioner
        args: ["--volume-name-prefix=csivol"]
        # sdc-monitor is disabled by default, due to high CPU usage
      - name: sdc-monitor
        enabled: false
        envs:
          - name: HOST_PID
            value: "1"
          - name: MDM
            value: "10.xx.xx.xx,10.xx.xx.xx" # do not add mdm value here if it is present in secret
            # health monitor is disabled by default, refer to driver documentation before enabling it
            # Also set the env variable controller.envs.X_CSI_HEALTH_MONITOR_ENABLED  to "true".
            # Default monitor-interval: 60s
      - name: csi-external-health-monitor-controller
        enabled: false
        args: ["--monitor-interval=60s"]
    # Uncomment the following to configure how often external-provisioner polls the driver to detect changed capacity
    # Configure when the storageCapacity is set as "true"
    # Allowed values: 1m,2m,3m,...,10m,...,60m etc. Default value: 5m
    # - name: provisioner
    #  args: ["--capacity-poll-interval=5m"]

    controller:
      envs:
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from Controller plugin - volume condition.
        # Install the 'external-health-monitor' sidecar accordingly.
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        # X_CSI_POWERFLEX_EXTERNAL_ACCESS: Allows to specify additional entries for hostAccess of NFS volumes. Both single IP address and subnet are valid entries.
        # Allowed Values: x.x.x.x/xx or x.x.x.x
        # Default Value: None
        - name: X_CSI_POWERFLEX_EXTERNAL_ACCESS
          value:
      # "controller.nodeSelector" defines what nodes would be selected for pods of controller deployment
      # Leave as blank to use all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # "controller.tolerations" defines tolerations that would be applied to controller deployment
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"
    node:
      envs:
        # X_CSI_SDC_ENABLED: Enable/Disable SDC
        # Allowed values:
        #    true: enable SDC
        #    false: disable SDC
        # Default value: true
        - name: X_CSI_SDC_ENABLED
          value: "true"
        # X_CSI_APPROVE_SDC_ENABLED: Enables/Disable SDC approval
        # Allowed values:
        #    true: enable SDC approval based on either GUID or IP address, depending on the restricted SDC mode configured in PowerFlex system
        #    false: disable SDC approval based on either GUID or IP address, depending on the restricted SDC mode configured in PowerFlex system
        # Default value: false
        - name: X_CSI_APPROVE_SDC_ENABLED
          value: "false"
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from node plugin - volume usage
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        # X_CSI_RENAME_SDC_ENABLED: Enable/Disable rename of SDC
        # Allowed values:
        #   true: enable renaming
        #   false: disable renaming
        # Default value: false
        - name: X_CSI_RENAME_SDC_ENABLED
          value: "false"
        # X_CSI_RENAME_SDC_PREFIX: defines a string for prefix of the SDC name.
        # "prefix" + "worker_node_hostname" should not exceed 31 chars.
        # Default value: none
        # Examples: "rhel-sdc", "sdc-test"
        - name: X_CSI_RENAME_SDC_PREFIX
          value: ""
        # X_CSI_MAX_VOLUMES_PER_NODE: Defines the maximum PowerFlex volumes that can be created per node
        # Allowed values: Any value greater than or equal to 0
        # If value is zero Container Orchestrator shall decide how many volumes of this type can be published by the controller to the node.
        # This limit is applicable to all the nodes in the cluster for which node label 'maxVxflexosVolumesPerNode' is not set.
        # Default value: "0"
        - name: X_CSI_MAX_VOLUMES_PER_NODE
          value: "0"
        # X_CSI_SDC_SFTP_REPO_ENABLED: Enable/Disable SDC SFTP repository
        - name: X_CSI_SDC_SFTP_REPO_ENABLED
          value: "false"
      # "node.nodeSelector" defines what nodes would be selected for pods of node daemonset
      # Leave as blank to use all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # "node.tolerations" defines tolerations that would be applied to node daemonset
      # Leave as blank to install node driver only on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if CSM for Resiliency and CSI Driver pods monitor is enabled
      #  - key: "offline.vxflexos.storage.dell.com"
      #    operator: "Exists"
      #    effect: "NoSchedule"
      #  - key: "vxflexos.podmon.storage.dell.com"
      #    operator: "Exists"
      #    effect: "NoSchedule"
    initContainers:
      - imagePullPolicy: IfNotPresent
        name: sdc
        envs:
          - name: MDM
            value: "10.xx.xx.xx,10.xx.xx.xx" # provide MDM value
          - name: REPO_ADDRESS
            value: "sftp://0.0.0.0" # SFTP/private repository address. Format: "protocol://address"
          - name: REPO_USER
            value: "sdcRepoUser" # provide username to authenticate to the SFTP repo
          - name: MODULE_SIGCHECK
            value: "0"
  modules:
    # Authorization: enable csm-authorization for RBAC
    - name: authorization
      # enabled: Enable/Disable csm-authorization
      enabled: false
      components:
        - name: karavi-authorization-proxy
          envs:
            # proxyHost: hostname of the csm-authorization server
            # Default value: none
            - name: "PROXY_HOST"
              value: "csm-authorization.com"
            # skipCertificateValidation: Enable/Disable certificate validation of the csm-authorization server
            # Default value: "true"
            - name: "SKIP_CERTIFICATE_VALIDATION"
              value: "true"
    # observability: allows to configure observability
    - name: observability
      # enabled: Enable/Disable observability
      # Default value: false
      enabled: false
      components:
        - name: otel-collector
          # enabled: Enable/Disable OpenTelemetry Collector
          # Default value: false
          enabled: false
          # certificate: base64-encoded certificate for cert/private-key pair -- add cert here to use custom certificates
          #  for self-signed certs, leave empty string
          # Allowed values: string
          certificate: ""
          # privateKey: base64-encoded private key for cert/private-key pair -- add private key here to use custom certificates
          #  for self-signed certs, leave empty string
          # Allowed values: string
          privateKey: ""
        # enabled: Enable/Disable cert-manager
        # Allowed values:
        #   true: enable deployment of cert-manager
        #   false: disable deployment of cert-manager only if it's already deployed
        # Default value: false
        - name: cert-manager
          enabled: false
        - name: metrics-powerflex
          # enabled: Enable/Disable PowerFlex metrics
          # Default value: false
          enabled: false
          envs:
            # POWERFLEX_MAX_CONCURRENT_QUERIES: set the default max concurrent queries to PowerFlex
            # Allowed values: int
            # Default value: 10
            - name: "POWERFLEX_MAX_CONCURRENT_QUERIES"
              value: "10"
            # POWERFLEX_SDC_METRICS_ENABLED: enable/disable collection of sdc metrics
            # Allowed values: ture, false
            # Default value: true
            - name: "POWERFLEX_SDC_METRICS_ENABLED"
              value: "true"
            # POWERFLEX_VOLUME_METRICS_ENABLED: enable/disable collection of volume metrics
            # Allowed values: ture, false
            # Default value: true
            - name: "POWERFLEX_VOLUME_METRICS_ENABLED"
              value: "true"
            # POWERFLEX_STORAGE_POOL_METRICS_ENABLED: enable/disable collection of storage pool metrics
            # Allowed values: ture, false
            # Default value: true
            - name: "POWERFLEX_STORAGE_POOL_METRICS_ENABLED"
              value: "true"
            # POWERFLEX_SDC_IO_POLL_FREQUENCY: set polling frequency to get sdc metrics data
            # Allowed values: int
            # Default value: 10
            - name: "POWERFLEX_SDC_IO_POLL_FREQUENCY"
              value: "10"
            # POWERFLEX_VOLUME_IO_POLL_FREQUENCY: set polling frequency to get volume metrics data
            # Allowed values: int
            # Default value: 10
            - name: "POWERFLEX_VOLUME_IO_POLL_FREQUENCY"
              value: "10"
            # POWERFLEX_STORAGE_POOL_POLL_FREQUENCY: set polling frequency to get Quota capacity metrics data
            # Allowed values: int
            # Default value: 10
            - name: "POWERFLEX_STORAGE_POOL_POLL_FREQUENCY"
              value: "10"
            # POWERFLEX_TOPOLOGY_METRICS_ENABLED: enable/disable collection of topology metrics
            # Allowed values: ture, false
            # Default value: true
            - name: "POWERFLEX_TOPOLOGY_METRICS_ENABLED"
              value: "true"
            # POWERFLEX_TOPOLOGY_METRICS_POLL_FREQUENCY: set polling frequency to get topology metrics data
            # Allowed values: int
            # Default value: 30
            - name: "POWERFLEX_TOPOLOGY_METRICS_POLL_FREQUENCY"
              value: "30"
            # PowerFlex metrics log level
            # Valid values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, PANIC
            # Default value: "INFO"
            - name: "POWERFLEX_LOG_LEVEL"
              value: "INFO"
            # PowerFlex Metrics Output logs in the specified format
            # Valid values: TEXT, JSON
            # Default value: "TEXT"
            - name: "POWERFLEX_LOG_FORMAT"
              value: "TEXT"
            # Otel collector address
            # Allowed values: String
            # Default value: "otel-collector:55680"
            - name: "COLLECTOR_ADDRESS"
              value: "otel-collector:55680"
    # Replication: allows to configure replication
    # Replication CRDs must be installed before installing driver
    - name: replication
      # enabled: Enable/Disable replication feature
      # Allowed values:
      #   true: enable replication feature(install dell-csi-replicator sidecar)
      #   false: disable replication feature(do not install dell-csi-replicator sidecar)
      # Default value: false
      enabled: false
      components:
        - name: dell-csi-replicator
          envs:
            # replicationPrefix: prefix to prepend to storage classes parameters
            # Allowed values: string
            # Default value: replication.storage.dell.com
            - name: "X_CSI_REPLICATION_PREFIX"
              value: "replication.storage.dell.com"
            # replicationContextPrefix: prefix to use for naming of resources created by replication feature
            # Allowed values: string
            - name: "X_CSI_REPLICATION_CONTEXT_PREFIX"
              value: "powerflex"
        - name: dell-replication-controller-manager
          envs:
            # Replication log level
            # Allowed values: "error", "warn"/"warning", "info", "debug"
            # Default value: "debug"
            - name: "REPLICATION_CTRL_LOG_LEVEL"
              value: "debug"
            # replicas: Defines number of controller replicas
            # Allowed values: int
            # Default value: 1
            - name: "REPLICATION_CTRL_REPLICAS"
              value: "1"
            # retryIntervalMin: Initial retry interval of failed reconcile request.
            # It doubles with each failure, upto retry-interval-max
            # Allowed values: time
            - name: "RETRY_INTERVAL_MIN"
              value: "1s"
            # RETRY_INTERVAL_MAX: Maximum retry interval of failed reconcile request
            # Allowed values: time
            - name: "RETRY_INTERVAL_MAX"
              value: "5m"
            # DISABLE_PVC_REMAP: Disable PVC remapping for replication in single cluster configuration
            # Allowed values:
            #   true: Disable replication feature(install dell-csi-replicator sidecar)
            #   false: disable replication feature(do not install dell-csi-replicator sidecar)
            # Default value: false
            - name: "DISABLE_PVC_REMAP"
              value: "false"
            # REPLICATION_ALLOW_PVC_CREATION_ON_TARGET: It Creates PVC on target cluster using replicated PV.
            # Allowed values:
            #   true: It creates a PVC on target cluster against replicated PV
            #   false: simply updates claimref on replicated PV on target cluster without actually creating a PVC
            # Default value: false
            - name: "REPLICATION_ALLOW_PVC_CREATION_ON_TARGET"
              value: "false"
    - name: resiliency
      # enabled: Enable/Disable Resiliency feature
      # Allowed values:
      #   true: enable Resiliency feature(deploy podmon sidecar)
      #   false: disable Resiliency feature(do not deploy podmon sidecar)
      # Default value: false
      enabled: false
      components:
        - name: podmon-controller
          imagePullPolicy: IfNotPresent
          args:
            - "--labelvalue=csi-vxflexos"
            - "--skipArrayConnectionValidation=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--arrayConnectivityPollRate=5"
            - "--arrayConnectivityConnectionLossThreshold=3"
            # Below 3 args should not be modified.
            - "--csisock=unix:/var/run/csi/csi.sock"
            - "--mode=controller"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
        - name: podmon-node
          imagePullPolicy: IfNotPresent
          envs:
            # podmonAPIPort: Defines the port to be used within the kubernetes cluster
            # Allowed values: Any valid and free port (string)
            # Default value: 8083
            - name: "X_CSI_PODMON_API_PORT"
              value: "8083"
          args:
            - "--labelvalue=csi-vxflexos"
            - "--leaderelection=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--arrayConnectivityPollRate=5"
            # Below 3 args should not be modified.
            - "--csisock=unix:/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock"
            - "--mode=node"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
