apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: <BACKUPSTORAGELOCATION_NAME>
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: application-mobility-velero
    app.kubernetes.io/instance: application-mobility
spec:
  provider: <CONFIGURATION_PROVIDER>
  accessMode: ReadWrite
  objectStorage:
    bucket: <BUCKET_NAME>
    cacert: <BUCKET_CACERT>
  default: true
  config:
    region: <BACKUP_REGION_URL>
    s3ForcePathStyle: true
    s3Url: <BACKUP_STORAGE_URL>
