apiVersion: v1
kind: Service
metadata:
  name: csipowermax-reverseproxy
  namespace: <DriverDefaultReleaseNamespace>
spec:
  ports:
    - port: <X_CSI_REVPROXY_PORT>
      protocol: TCP
      targetPort: 2222
  selector:
    app: <DriverDefaultReleaseName>-controller
  type: ClusterIP
