apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: <NAMESPACE>
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karavi-auth
  namespace: <NAMESPACE>
spec:
  secretName: karavi-auth-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - dellemc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - <AUTHORIZATION_HOSTNAME>
  - <PROXY_INGRESS_HOST>
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
