apiVersion: v1
data:
  # replace with actual base64-encoded certificate
  tls.crt: <BASE64_CERTIFICATE>
  # replace with actual base64-encoded private key
  tls.key: <BASE64_PRIVATE_KEY>
kind: Secret
type: kubernetes.io/tls
metadata:
  name: user-provided-tls
  namespace: <NAMESPACE>
