apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-vxflexos.dellemc.com
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: restricted
spec:
  fsGroupPolicy: ReadWriteOnceWithFSType
  attachRequired: true
  podInfoOnMount: true
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
