# Copyright © 2024-2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.
name: CSM Common Workflows
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      images:
        description: "Multi-line string of images"
        type: string
        required: false
      build-images-cmd:
        description: "Command to build the image(s)"
        type: string
        required: false
      build-binary-cmd:
        description: "Command to build the binary"
        type: string
        required: false
      binary-path:
        description: "Path to the binary"
        type: string
        required: false
  pull_request:
    branches: ["**"]

jobs:
  # golang static analysis checks
  go-static-analysis:
    name: Golang Validation
    uses: CSM/actions/.github/workflows/go-static-analysis.yaml@main
    secrets: inherit

  common:
    name: Quality Checks
    uses: CSM/actions/.github/workflows/csm-common.yml@usr/evgeny/bd-cve-analyzer-action
    with:
      images: |
        dell-csm-operator
      build-images-cmd: "make images"
    secrets: inherit
