name: Common Workflows
# yamllint sees the below line as a true or false value instead of an 'on' trigger
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  # golang static analysis checks
  go-static-analysis:
    uses: CSM/actions/.github/workflows/go-static-analysis.yaml@main
    name: Golang Validation

  common:
    name: Quality Checks
    uses: CSM/actions/.github/workflows/csm-common.yml@main
    with:
      images: |
        <insert or delete input>
      build-images-cmd: "<insert or delete input>"
      binary-path: "<insert or delete input>"
      build-binary-cmd: "<insert or delete input>"
    secrets: inherit
