#!/bin/bash

# Copyright 2025 DELL Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CSM Operator version update consolidated
# reusable workflow
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      csm-version:
        description: 'CSM version, ex: v1.14.0, v1.15.0, ...'
        required: true
      operator-version:
        description: "CSM Operator Version (v1.11.0)"
        required: true
        type: string
jobs:
  version-update:
    uses: CSM/actions/.github/workflows/csm-operator-version-update-all.yaml@main
    name: Operator version update
    with:
      csm-version: ${{ inputs.csm-version }}
      operator-version: ${{ inputs.operator-version}}
    secrets: inherit
