# Copyright © 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.

# Reusable workflow to perform go version update on Golang based projects
name: Go Version Update

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  repository_dispatch:
    types: [go-update-workflow]

jobs:
  # go version update
  go-version-update:
    uses: CSM/actions/.github/workflows/go-version-workflow.yaml@main
    name: Go Version Update
    secrets: inherit
