# Copyright © 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.

# Reusable workflow to perform image version update on Golang based projects
name: Image Version Update

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (major, minor, patch) Ex: minor"
        required: true
  repository_dispatch:
    types: [image-update-workflow]

jobs:
  # image version update
  image-version-update:
    uses: CSM/actions/.github/workflows/image-version-workflow.yaml@main
    with:
      version: "${{ github.event.inputs.version || 'minor' }}"
    secrets: inherit
