name: Update CSM Operator version
# reusable workflow
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      csm-version:
        description: 'CSM program version, ex: v1.12.0, v1.13.0, ...'
        required: true
      latest-version:
        description: 'Latest operator version, ex: v1.7.0, v1.8.0, ...'
        required: true
      existing-version:
        description: 'Existing operator version, ex: v1.6.0, 1.7.0, ...'
        required: true
jobs:
  version-update:
    uses: dell/common-github-actions/.github/workflows/operator-version-update.yaml@operator-version-update-action
    name: Operator version update
    with:
      latest-version: ${{ github.event.inputs.latest-version }}
      existing-version: ${{ github.event.inputs.existing-version }}
      csm-version: ${{ github.event.inputs.csm-version }}
    secrets: inherit
