# Copyright © 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.

# Reusable workflow to perform updates of Dell client libraries to latest commits
name: Dell Libraries Commit Update
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  repository_dispatch:
    types: [latest-commits-libraries]

jobs:
  package-update:
    uses: CSM/actions/.github/workflows/update-libraries-to-commits.yml@main
    name: Dell Libraries Update
    secrets: inherit
