# Copyright © 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Dell Technologies, Dell and other trademarks are trademarks of Dell Inc.
# or its subsidiaries. Other trademarks may be trademarks of their respective
# owners.

# Reusable workflow to perform updates of Dell client libraries
name: Dell OCP Sample and ConfigMap Files Update
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      version:
        description: "Input the latest OCP version base on what is found in the OCP certified Redhat repository. i.e (1.10.0)"
        required: true
        type: string
      driver-version:
        description: "Add a csm version i.e (1.16.2), otherwise defaults to `latest`"
        required: false
        type: string
        default: "latest"
      cosi-version:
        description: "Add a specific cosi version i.e (1.0.0), otherwise defaults to `latest`"
        required: false
        type: string
        default: "latest"
env:
  BRANCH_NAME: "usr/github-actions/update-ocp-samples-${{ inputs.version }}"
  GH_HOST: ${{ vars.DELL_GITHUB_URL }}
  GH_ENTERPRISE_TOKEN: ${{ secrets.DELL_GITHUB_TOKEN_RW }}

jobs:
  run-script-job:
    runs-on: isg-ocp-x86-small
    steps:
      - name: Checkout csm operator repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Set Up Go Environment
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install yq
        run: |
          go install github.com/mikefarah/yq/v4@latest

      - name: Run OCP Sample files update script
        run: |
          OCP_VERSION=${{ inputs.version }}
          DRIVER_VERSION=${{ inputs.driver-version }}
          COSI_VERSION=${{ inputs.cosi-version }}
          bash ./.github/scripts/csm-update-ocp-examples.sh $OCP_VERSION $DRIVER_VERSION $COSI_VERSION

      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v3.1.1
        id: generate-token
        with:
          app-id: ${{ vars.CSM_RELEASE_APP_ID }}
          private-key: ${{ secrets.CSM_RELEASE_APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: ghe-actions/peter-evans-create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ env.BRANCH_NAME }}
          commit-message: "update ocp samples and configMap for version ${{ inputs.version }}"
          title: "Update OCP samples and configMap for version ${{ inputs.version }}"
          body: |
            This PR automatically creates all the sample and configMap files for ${{ inputs.version }} in OCP.
            Auto-generated by [github-actions](https://eos2git.cec.lab.emc.com/CSM/csm-operator)
          sign-commits: true
          delete-branch: true
